import json
import re

# This is a data structure with representing our knowledge base.
# NOTE: If you are adding new entries try to make the field name
#   self explanatory.
KNOWLEDGE_BASE = {}

# Adds information to the knowledge base (KB)
# Args - 
#   tuple: list of string 
#   kb_subtree (optional): a defaultdict that represents a KB tree  
def addToKB(tuple, kb_subtree = KNOWLEDGE_BASE):
    current_entry = kb_subtree
    for i in range(len(tuple)):
        if not tuple[i] in current_entry:
            current_entry[tuple[i]] = {}
        current_entry = current_entry[tuple[i]]

# Verifies if tuple is in knowledge base (KB)
# Args - 
#   tuple: list of string
#   kb_subtree (optional): a defaultdict that represents a KB tree
#   regex (optional): boolean value, if true will match the keys in the
#       dictionary using regex.
# Returns -
#   True if tuple is part of the KB.
def isInKB(tuple, kb_subtree = KNOWLEDGE_BASE, regex = False):
    return getKBSubtree(tuple, kb_subtree, regex) is not None

# Gets a subtree of the knowledge base associated with the tuple.
# E.g. running getKBSubtree(["ingredients"]]) will return a dict
# where the list of keys are ingredients.
# Args - 
#   tuple: list of string
#   kb_subtree (optional): a defaultdict that represents a KB tree
#   regex (optional): boolean value, if true will match the keys in the
#       dictionary using regex. If more than one key matches the regex,
#       will return the first match.   
# Returns -
#   A dict that is a subtree of the KB or None if not present.
#   Might return a list of dicts if regex is True.
def getKBSubtree(tuple, kb_subtree = KNOWLEDGE_BASE, regex=False):
    current_entry = kb_subtree
    for i in range(len(tuple)):
        if regex:
            matched_any_key = False
            for key in current_entry.keys():
                if re.match(tuple[i], key) is not None:
                    current_entry = current_entry[key]
                    matched_any_key = True
                    break
            if not matched_any_key:
                return None
        else:
            if not tuple[i] in current_entry:
                return None
            current_entry = current_entry[tuple[i]]
    return current_entry

# Gets a subtree of the knowledge base associated with the tuple,
# removing any nodes that don't match regex.
# Args - 
#   tuple: list of string
#   kb_subtree (optional): a defaultdict that represents a KB tree
# Returns -
#   returns the dicts, pruning nodes that are not part of regex.
def getKBPrunedByRegex(tuple, kb_subtree = KNOWLEDGE_BASE):
    # base case
    if (len(tuple) == 0):
        return {}

    # continue search        
    return_dict = {}
    for key in kb_subtree.keys():
            if re.match(tuple[0], key) is not None:
                key_subtree = getKBPrunedByRegex(tuple = tuple[1:], kb_subtree = kb_subtree[key])
                if len(key_subtree) > 0 or len(tuple[1:]) == 0:
                    return_dict[key] = key_subtree

    return return_dict

# Adds information to the knowledge base (KB)
# Args - 
#   knowledge_subtre (optional): a defaultdict that represents a KB tree
def prettyPrintKBsubtree(kb_subtree = KNOWLEDGE_BASE):
    print(json.dumps(kb_subtree, sort_keys=True, indent=4))

####################################################################
### List of Ingredients

## Tagged

"""
addToKB(["ingredients", "bok choy", "chinese"])
addToKB(["ingredients", "bok choy", "veggie"])
addToKB(["ingredients", "snake beans", "chinese"])
addToKB(["ingredients", "snake beans", "bean"])
addToKB(["ingredients", "snake beans", "veggie"])
addToKB(["ingredients", "sorrel leaves", "veggie"])
addToKB(["ingredients", "sorrel leaves", "sour"])
addToKB(["ingredients", "rocket leaves", "veggie"])
addToKB(["ingredients", "rocket leaves", "garnish"])
addToKB(["ingredients", "rocket leaves", "leaf"])
addToKB(["ingredients", "drumstick", "veggie"])
addToKB(["ingredients", "drumstick", "soup"])
addToKB(["ingredients", "cherry tomatoes", "fruit"])
addToKB(["ingredients", "kaffir lime", "fruit"])
addToKB(["ingredients", "kaffir lime", "citrus"])
addToKB(["ingredients", "kaffir lime", "sour"])
addToKB(["ingredients", "plantain", "fruit"])
addToKB(["ingredients", "plantain", "starchy"])
addToKB(["ingredients", "turnip", "veggie"])
addToKB(["ingredients", "turnip", "root"])
addToKB(["ingredients", "sweet potatoes", "veggie"])
addToKB(["ingredients", "sweet potatoes", "root"])
addToKB(["ingredients", "sweet potatoes", "sweet"])
addToKB(["ingredients", "sweet potatoes", "starchy"])
addToKB(["ingredients", "round gourd", "veggie"])
addToKB(["ingredients", "round gourd", "squash"])
addToKB(["ingredients", "round gourd", "indian"])
addToKB(["ingredients", "ridge gourd", "fruit"])
addToKB(["ingredients", "ridge gourd", "indian"])
addToKB(["ingredients", "ridge gourd", "chinese"])
addToKB(["ingredients", "pimiento", "pepper"])
addToKB(["ingredients", "pimiento", "sweet"])
addToKB(["ingredients", "spinach", "veggie"])
addToKB(["ingredients", "spinach", "leaf"])
addToKB(["ingredients", "onion", "root"])
addToKB(["ingredients", "onion", "veggie"])
addToKB(["ingredients", "onion", "chinese"])
addToKB(["ingredients", "mustard leaves", "veggie"])
addToKB(["ingredients", "mustard leaves", "chinese"])
addToKB(["ingredients", "mushroom", "fleshy"])
addToKB(["ingredients", "mushroom", "fungus"])
addToKB(["ingredients", "mushroom", "chinese"])
addToKB(["ingredients", "mushroom", "veggie"])
addToKB(["ingredients", "radish", "root"])
addToKB(["ingredients", "radish", "veggie"])
addToKB(["ingredients", "radish", "chinese"])
addToKB(["ingredients", "shallots", "onion"])
addToKB(["ingredients", "shallots", "veggie"])
addToKB(["ingredients", "lettuce", "veggie"])
addToKB(["ingredients", "lettuce", "leaf"])
addToKB(["ingredients", "lettuce", "chinese"])
addToKB(["ingredients", "leek", "leaf"])
addToKB(["ingredients", "leek", "onion"])
addToKB(["ingredients", "pumpkin", "squash"])
addToKB(["ingredients", "pumpkin", "chinese"])
addToKB(["ingredients", "yam", "root"])
addToKB(["ingredients", "yam", "veggie"])
addToKB(["ingredients", "jalapeno", "pepper"])
addToKB(["ingredients", "jalapeno", "hot"])
addToKB(["ingredients", "jackfruit", "indian"])
addToKB(["ingredients", "jackfruit", "fruit"])
addToKB(["ingredients", "jackfruit", "starchy"])
addToKB(["ingredients", "horseradish", "root"])
addToKB(["ingredients", "horseradish", "veggie"])
addToKB(["ingredients", "horseradish", "spice"])
addToKB(["ingredients", "spring onion", "onion"])
addToKB(["ingredients", "spring onion", "veggie"])
addToKB(["ingredients", "spring onion", "root"])
addToKB(["ingredients", "green peas", "veggie"])
addToKB(["ingredients", "green peas", "chinese"])
addToKB(["ingredients", "green chillies", "pepper"])
addToKB(["ingredients", "green chillies", "hot"])
addToKB(["ingredients", "cluster beans", "veggie"])
addToKB(["ingredients", "gherkins", "pickled"])
addToKB(["ingredients", "gherkins", "veggie"])
addToKB(["ingredients", "garlic", "onion"])
addToKB(["ingredients", "garlic", "chinese"])
addToKB(["ingredients", "garlic", "seasoning"])
addToKB(["ingredients", "garlic", "root"])
addToKB(["ingredients", "french beans", "veggie"])
addToKB(["ingredients", "french beans", "pod"])
addToKB(["ingredients", "french beans", "chinese"])
addToKB(["ingredients", "fenugreek", "seed"])
addToKB(["ingredients", "fenugreek", "leaf"])
addToKB(["ingredients", "cucumber", "veggie"])
addToKB(["ingredients", "cucumber", "gourd"])
addToKB(["ingredients", "zucchini", "veggie"])
addToKB(["ingredients", "zucchini", "squash"])
addToKB(["ingredients", "corn", "grain"])
addToKB(["ingredients", "corn", "veggie"])
addToKB(["ingredients", "corn", "chinese"])
addToKB(["ingredients", "shiitake mushroom", "veggie"])
addToKB(["ingredients", "shiitake mushroom", "fungus"])
addToKB(["ingredients", "shiitake mushroom", "fleshy"])
addToKB(["ingredients", "shiitake mushroom", "chinese"])
addToKB(["ingredients", "celery", "root"])
addToKB(["ingredients", "celery", "veggie"])
addToKB(["ingredients", "celery", "soup"])
addToKB(["ingredients", "cauliflower", "veggie"])
addToKB(["ingredients", "cauliflower", "florets"])
addToKB(["ingredients", "carrot", "root"])
addToKB(["ingredients", "carrot", "veggie"])
addToKB(["ingredients", "carrot", "chinese"])
addToKB(["ingredients", "capsicum", "pepper"])
addToKB(["ingredients", "capsicum", "sweet"])
addToKB(["ingredients", "capsicum", "chinese"])
addToKB(["ingredients", "capers", "salted"])
addToKB(["ingredients", "capers", "pickled"])
addToKB(["ingredients", "capers", "italian"])
addToKB(["ingredients", "capers", "garnish"])
addToKB(["ingredients", "broccoli", "veggie"])
addToKB(["ingredients", "broccoli", "florets"])
addToKB(["ingredients", "broad beans", "bean"])
addToKB(["ingredients", "broad beans", "chinese"])
addToKB(["ingredients", "broad beans", "veggie"])
addToKB(["ingredients", "bottle gourd", "toxic"])
addToKB(["ingredients", "bottle gourd", "gourd"])
addToKB(["ingredients", "bottle gourd", "melon"])
addToKB(["ingredients", "bottle gourd", "chinese"])
addToKB(["ingredients", "bitter gourd", "fruit"])
addToKB(["ingredients", "bitter gourd", "melon"])
addToKB(["ingredients", "bitter gourd", "gourd"])
addToKB(["ingredients", "bitter gourd", "chinese"])
addToKB(["ingredients", "lady finger", "veggie"])
addToKB(["ingredients", "lady finger", "indian"])
addToKB(["ingredients", "lotus stem", "indian"])
addToKB(["ingredients", "lotus stem", "veggie"])
addToKB(["ingredients", "lotus stem", "pickled"])
addToKB(["ingredients", "bell pepper", "pepper"])
addToKB(["ingredients", "bell pepper", "sweet"])
addToKB(["ingredients", "bell pepper", "chinese"])
addToKB(["ingredients", "bell pepper", "veggie"])
addToKB(["ingredients", "beetroot", "root"])
addToKB(["ingredients", "beetroot", "veggie"])
addToKB(["ingredients", "pigweed", "chinese"])
addToKB(["ingredients", "cabbage", "leaf"])
addToKB(["ingredients", "cabbage", "veggie"])
addToKB(["ingredients", "cabbage", "root"])
addToKB(["ingredients", "bamboo shoot", "toxic"])
addToKB(["ingredients", "bamboo shoot", "chinese"])
addToKB(["ingredients", "baby corn", "grain"])
addToKB(["ingredients", "baby corn", "veggie"])
addToKB(["ingredients", "baby corn", "chinese"])
addToKB(["ingredients", "avocado", "berry"])
addToKB(["ingredients", "avocado", "veggie"])
addToKB(["ingredients", "eggplant", "fruit"])
addToKB(["ingredients", "eggplant", "chinese"])
addToKB(["ingredients", "asparagus", "veggie"])
addToKB(["ingredients", "asparagus", "stalk"])
addToKB(["ingredients", "ash gourd", "gourd"])
addToKB(["ingredients", "ash gourd", "melon"])
addToKB(["ingredients", "ash gourd", "veggie"])
addToKB(["ingredients", "ash gourd", "chinese"])
addToKB(["ingredients", "ash gourd", "fruit"])
addToKB(["ingredients", "artichoke", "veggie"])
addToKB(["ingredients", "artichoke", "chinese"])
addToKB(["ingredients", "colocasia", "indian"])
addToKB(["ingredients", "colocasia", "leaf"])
addToKB(["ingredients", "potatoes", "starchy"])
addToKB(["ingredients", "potatoes", "root"])
addToKB(["ingredients", "potatoes", "veggie"])
addToKB(["ingredients", "ginger", "spice"])
addToKB(["ingredients", "ginger", "chinese"])
addToKB(["ingredients", "ginger", "pickled"])
addToKB(["ingredients", "coriander powder", "chinese"])
addToKB(["ingredients", "coriander powder", "garnish"])
addToKB(["ingredients", "coriander powder", "veggie"])
addToKB(["ingredients", "chives", "veggie"])
addToKB(["ingredients", "chives", "onion"])
addToKB(["ingredients", "chives", "soup"])
addToKB(["ingredients", "galangal", "spice"])
addToKB(["ingredients", "galangal", "chinese"])
addToKB(["ingredients", "tulsi", "herb"])
addToKB(["ingredients", "tulsi", "aromatic"])
addToKB(["ingredients", "sage", "aromatic"])
addToKB(["ingredients", "sage", "herb"])
addToKB(["ingredients", "sage", "italian"])
addToKB(["ingredients", "rosemary", "herb"])
addToKB(["ingredients", "rosemary", "bitter"])
addToKB(["ingredients", "rosemary", "aromatic"])
addToKB(["ingredients", "yellow chillies", "pepper"])
addToKB(["ingredients", "yellow chillies", "veggie"])
addToKB(["ingredients", "oregano", "italian"])
addToKB(["ingredients", "oregano", "herb"])
addToKB(["ingredients", "oregano", "aromatic"])
addToKB(["ingredients", "oregano", "warm"])
addToKB(["ingredients", "oregano", "bitter"])
addToKB(["ingredients", "nasturtium", "veggie"])
addToKB(["ingredients", "nasturtium", "leaf"])
addToKB(["ingredients", "salt", "seasoning"])
addToKB(["ingredients", "salt", "salty"])
addToKB(["ingredients", "mustard powder", "spice"])
addToKB(["ingredients", "mustard powder", "tangy"])
addToKB(["ingredients", "paprika", "spice"])
addToKB(["ingredients", "mint leaves", "leaf"])
addToKB(["ingredients", "mint leaves", "herb"])
addToKB(["ingredients", "mint leaves", "aromatic"])
addToKB(["ingredients", "marjoram", "aromatic"])
addToKB(["ingredients", "marjoram", "leaf"])
addToKB(["ingredients", "marjoram", "herb"])
addToKB(["ingredients", "marjoram", "italian"])
addToKB(["ingredients", "lemongrass", "herb"])
addToKB(["ingredients", "lemongrass", "soup"])
addToKB(["ingredients", "lemongrass", "leaf"])
addToKB(["ingredients", "red chili", "pepper"])
addToKB(["ingredients", "red chili", "hot"])
addToKB(["ingredients", "red chili", "veggie"])
addToKB(["ingredients", "saffron", "spice"])
addToKB(["ingredients", "saffron", "seasoning"])
addToKB(["ingredients", "dried fenugreek leaves", "veggie"])
addToKB(["ingredients", "dried fenugreek leaves", "leaf"])
addToKB(["ingredients", "kashmiri mirch", "powder"])
addToKB(["ingredients", "kashmiri mirch", "hot"])
addToKB(["ingredients", "kashmiri mirch", "pepper"])
addToKB(["ingredients", "onion seeds", "seed"])
addToKB(["ingredients", "onion seeds", "seasoning"])
addToKB(["ingredients", "mace", "spice"])
addToKB(["ingredients", "mace", "sweet"])
addToKB(["ingredients", "nutmeg", "spice"])
addToKB(["ingredients", "nutmeg", "aromatic"])
addToKB(["ingredients", "herbs", "herb"])
addToKB(["ingredients", "thyme", "herb"])
addToKB(["ingredients", "thyme", "aromatic"])
addToKB(["ingredients", "turmeric", "powder"])
addToKB(["ingredients", "turmeric", "indian"])
addToKB(["ingredients", "five spice powder", "chinese"])
addToKB(["ingredients", "five spice powder", "spice"])
addToKB(["ingredients", "fennel", "herb"])
addToKB(["ingredients", "fennel", "aromatic"])
addToKB(["ingredients", "green cardamom", "indian"])
addToKB(["ingredients", "green cardamom", "spice"])
addToKB(["ingredients", "green cardamom", "pods"])
addToKB(["ingredients", "dry ginger powder", "powder"])
addToKB(["ingredients", "dry ginger powder", "spice"])
addToKB(["ingredients", "dry ginger powder", "aromatic"])
addToKB(["ingredients", "dill", "herb"])
addToKB(["ingredients", "dill", "spice"])
addToKB(["ingredients", "dill", "chinese"])
addToKB(["ingredients", "curry leaves", "leaf"])
addToKB(["ingredients", "curry leaves", "indian"])
addToKB(["ingredients", "curry leaves", "curry"])
addToKB(["ingredients", "cumin seeds", "seed"])
addToKB(["ingredients", "cumin seeds", "spice"])
addToKB(["ingredients", "cumin seeds", "indian"])
addToKB(["ingredients", "coriander seeds", "seed"])
addToKB(["ingredients", "coriander seeds", "chinese"])
addToKB(["ingredients", "coriander leaves", "leaf"])
addToKB(["ingredients", "coriander leaves", "chinese"])
addToKB(["ingredients", "cloves", "aromatic"])
addToKB(["ingredients", "cloves", "spice"])
addToKB(["ingredients", "cloves", "indian"])
addToKB(["ingredients", "cinnamon", "spice"])
addToKB(["ingredients", "cinnamon", "aromatic"])
addToKB(["ingredients", "cinnamon", "additive"])
addToKB(["ingredients", "star anise", "seed"])
addToKB(["ingredients", "star anise", "chinese"])
addToKB(["ingredients", "cayenne", "pepper"])
addToKB(["ingredients", "caraway seeds", "seed"])
addToKB(["ingredients", "caraway seeds", "spice"])
addToKB(["ingredients", "caraway seeds", "root"])
addToKB(["ingredients", "cajun spices", "spice"])
addToKB(["ingredients", "rock salt", "spice"])
addToKB(["ingredients", "rock salt", "seasoning"])
addToKB(["ingredients", "black pepper", "seasoning"])
addToKB(["ingredients", "black pepper", "spice"])
addToKB(["ingredients", "black pepper", "chinese"])
addToKB(["ingredients", "black cumin", "seed"])
addToKB(["ingredients", "black cumin", "indian"])
addToKB(["ingredients", "bay leaf", "leaf"])
addToKB(["ingredients", "bay leaf", "bitter"])
addToKB(["ingredients", "bay leaf", "aromatic"])
addToKB(["ingredients", "basil", "leaf"])
addToKB(["ingredients", "basil", "aromatic"])
addToKB(["ingredients", "black cardamom", "pods"])
addToKB(["ingredients", "black cardamom", "smoky"])
addToKB(["ingredients", "black cardamom", "spice"])
addToKB(["ingredients", "asafoetida", "spice"])
addToKB(["ingredients", "asafoetida", "indian"])
addToKB(["ingredients", "aniseed", "seed"])
addToKB(["ingredients", "aniseed", "spice"])
addToKB(["ingredients", "raw mango powder", "powder"])
addToKB(["ingredients", "raw mango powder", "spice"])
addToKB(["ingredients", "raw mango powder", "indian"])
addToKB(["ingredients", "allspice", "spice"])
addToKB(["ingredients", "carom seeds", "seed"])
addToKB(["ingredients", "carom seeds", "spice"])
addToKB(["ingredients", "parsley", "herb"])
addToKB(["ingredients", "parsley", "spice"])
addToKB(["ingredients", "parsley", "veggie"])
addToKB(["ingredients", "acacia", "spice"])
addToKB(["ingredients", "acacia", "african"])
addToKB(["ingredients", "acacia", "australian"])
addToKB(["ingredients", "amaranth", "grain"])
addToKB(["ingredients", "flour", "grain"])
addToKB(["ingredients", "flour", "powder"])
addToKB(["ingredients", "flour", "cereal"])
addToKB(["ingredients", "flour", "italian"])
addToKB(["ingredients", "muesli", "oats"])
addToKB(["ingredients", "oats", "oats"])
addToKB(["ingredients", "oats", "cereal"])
addToKB(["ingredients", "oats", "grain"])
addToKB(["ingredients", "jowar", "grain"])
addToKB(["ingredients", "jowar", "african"])
addToKB(["ingredients", "jowar", "asian"])
addToKB(["ingredients", "jowar", "indian"])
addToKB(["ingredients", "brown rice", "chinese"])
addToKB(["ingredients", "brown rice", "grain"])
addToKB(["ingredients", "brown rice", "asian"])
addToKB(["ingredients", "arborio rice", "italian"])
addToKB(["ingredients", "arborio rice", "grain"])
addToKB(["ingredients", "arborio rice", "creamy"])
addToKB(["ingredients", "arborio rice", "chewy"])
addToKB(["ingredients", "water chestnut flour", "starch"])
addToKB(["ingredients", "water chestnut flour", "indian"])
addToKB(["ingredients", "water chestnut flour", "powder"])
addToKB(["ingredients", "barnyard millet", "cereal"])
addToKB(["ingredients", "barnyard millet", "grain"])
addToKB(["ingredients", "barnyard millet", "indian"])
addToKB(["ingredients", "barnyard millet", "african"])
addToKB(["ingredients", "tapioca", "starch"])
addToKB(["ingredients", "tapioca", "american"])
addToKB(["ingredients", "tapioca", "additive"])
addToKB(["ingredients", "tapioca", "powder"])
addToKB(["ingredients", "semolina", "powder"])
addToKB(["ingredients", "semolina", "wheat"])
addToKB(["ingredients", "finger millet", "cereal"])
addToKB(["ingredients", "finger millet", "grain"])
addToKB(["ingredients", "finger millet", "african"])
addToKB(["ingredients", "finger millet", "indian"])
addToKB(["ingredients", "puffed rice", "puffed"])
addToKB(["ingredients", "puffed rice", "grain"])
addToKB(["ingredients", "puffed rice", "indian"])
addToKB(["ingredients", "buckwheat", "grain"])
addToKB(["ingredients", "buckwheat", "asian"])
addToKB(["ingredients", "kidney beans", "bean"])
addToKB(["ingredients", "whole bengal gram", "legume"])
addToKB(["ingredients", "whole bengal gram", "indian"])
addToKB(["ingredients", "green gram", "bean"])
addToKB(["ingredients", "green gram", "chinese"])
addToKB(["ingredients", "green gram", "indian"])
addToKB(["ingredients", "all purpose flour", "grain"])
addToKB(["ingredients", "all purpose flour", "powder"])
addToKB(["ingredients", "all purpose flour", "cereal"])
addToKB(["ingredients", "whole brown lentils", "lentils"])
addToKB(["ingredients", "husked black gram", "indian"])
addToKB(["ingredients", "husked black gram", "lentil"])
addToKB(["ingredients", "husked green gram", "indian"])
addToKB(["ingredients", "husked green gram", "lentil"])
addToKB(["ingredients", "couscous", "grain"])
addToKB(["ingredients", "couscous", "african"])
addToKB(["ingredients", "cornmeal", "corn"])
addToKB(["ingredients", "cornmeal", "flour"])
addToKB(["ingredients", "pressed rice", "indian"])
addToKB(["ingredients", "pressed rice", "grain"])
addToKB(["ingredients", "rice", "cereal"])
addToKB(["ingredients", "rice", "grain"])
addToKB(["ingredients", "breadcrumbs", "breading"])
addToKB(["ingredients", "breadcrumbs", "garnish"])
addToKB(["ingredients", "breadcrumbs", "additive"])
addToKB(["ingredients", "bread", "bread"])
addToKB(["ingredients", "black-eyed beans", "legume"])
addToKB(["ingredients", "black-eyed beans", "bean"])
addToKB(["ingredients", "black gram", "bean"])
addToKB(["ingredients", "black beans", "bean"])
addToKB(["ingredients", "gram flour", "flour"])
addToKB(["ingredients", "gram flour", "indian"])
addToKB(["ingredients", "bengal gram", "legume"])
addToKB(["ingredients", "bengal gram", "indian"])
addToKB(["ingredients", "chickpeas", "legume"])
addToKB(["ingredients", "chickpeas", "indian"])
addToKB(["ingredients", "basmati rice", "indian"])
addToKB(["ingredients", "basmati rice", "rice"])
addToKB(["ingredients", "basmati rice", "grain"])
addToKB(["ingredients", "basmati rice", "cereal"])
addToKB(["ingredients", "basmati rice", "grain"])
addToKB(["ingredients", "barley", "cereal"])
addToKB(["ingredients", "pearl millet", "african"])
addToKB(["ingredients", "pearl millet", "indian"])
addToKB(["ingredients", "pearl millet", "cereal"])
addToKB(["ingredients", "pearl millet", "grain"])
addToKB(["ingredients", "whole wheat flour", "flour"])
addToKB(["ingredients", "whole wheat flour", "healthy"])
addToKB(["ingredients", "pigeon pea", "indian"])
addToKB(["ingredients", "pigeon pea", "legume"])
addToKB(["ingredients", "bean sprouts", "veggie"])
addToKB(["ingredients", "bean sprouts", "bean"])
addToKB(["ingredients", "beef", "meat"])
addToKB(["ingredients", "beef", "protein"])
addToKB(["ingredients", "beef", "cattle"])
addToKB(["ingredients", "veal", "meat"])
addToKB(["ingredients", "veal", "protein"])
addToKB(["ingredients", "veal", "cattle"])
addToKB(["ingredients", "grass fed chicken", "poultry"])
addToKB(["ingredients", "grass fed chicken", "protein"])
addToKB(["ingredients", "grass fed chicken", "humane"])
addToKB(["ingredients", "free range chicken", "poultry"])
addToKB(["ingredients", "free range chicken", "protein"])
addToKB(["ingredients", "free range chicken", "humane"])
addToKB(["ingredients", "free range chicken", "meat"])
addToKB(["ingredients", "organic chicken", "humane"])
addToKB(["ingredients", "organic chicken", "meat"])
addToKB(["ingredients", "organic chicken", "poultry"])
addToKB(["ingredients", "organic chicken", "protein"])
addToKB(["ingredients", "turkey", "poultry"])
addToKB(["ingredients", "turkey", "protein"])
addToKB(["ingredients", "turkey", "meat"])
addToKB(["ingredients", "skinned chicken", "poultry"])
addToKB(["ingredients", "skinned chicken", "meat"])
addToKB(["ingredients", "skinned chicken", "protein"])
addToKB(["ingredients", "pork", "meat"])
addToKB(["ingredients", "pork", "protein"])
addToKB(["ingredients", "pork", "pig"])
addToKB(["ingredients", "partridge", "poultry"])
addToKB(["ingredients", "partridge", "protein"])
addToKB(["ingredients", "partridge", "meat"])
addToKB(["ingredients", "meat stock", "broth"])
addToKB(["ingredients", "meat stock", "meat"])
addToKB(["ingredients", "keema", "indian"])
addToKB(["ingredients", "keema", "meat"])
addToKB(["ingredients", "mutton liver", "sheep"])
addToKB(["ingredients", "mutton liver", "entrails"])
addToKB(["ingredients", "mutton liver", "meat"])
addToKB(["ingredients", "mutton liver", "protein"])
addToKB(["ingredients", "ham", "pig"])
addToKB(["ingredients", "ham", "protein"])
addToKB(["ingredients", "ham", "meat"])
addToKB(["ingredients", "kidney meat", "organ"])
addToKB(["ingredients", "kidney meat", "meat"])
addToKB(["ingredients", "kidney meat", "protein"])
addToKB(["ingredients", "crab", "seafood"])
addToKB(["ingredients", "crab", "shellfish"])
addToKB(["ingredients", "chicken stock", "broth"])
addToKB(["ingredients", "chicken stock", "meat"])
addToKB(["ingredients", "chicken broth", "broth"])
addToKB(["ingredients", "chicken broth", "meat"])
addToKB(["ingredients", "chicken liver", "organ"])
addToKB(["ingredients", "chicken liver", "meat"])
addToKB(["ingredients", "chicken liver", "protein"])
addToKB(["ingredients", "chicken", "poultry"])
addToKB(["ingredients", "chicken", "meat"])
addToKB(["ingredients", "chicken", "protein"])
addToKB(["ingredients", "lamb meat", "meat"])
addToKB(["ingredients", "lamb meat", "protein"])
addToKB(["ingredients", "quail", "poultry"])
addToKB(["ingredients", "quail", "meat"])
addToKB(["ingredients", "quail", "protein"])
addToKB(["ingredients", "mutton", "goat"])
addToKB(["ingredients", "mutton", "meat"])
addToKB(["ingredients", "mutton", "protein"])
addToKB(["ingredients", "bacon", "pork"])
addToKB(["ingredients", "bacon", "cured"])
addToKB(["ingredients", "bacon", "meat"])
addToKB(["ingredients", "bacon", "protein"])
addToKB(["ingredients", "gruyere cheese", "cheese"])
addToKB(["ingredients", "gruyere cheese", "dairy"])
addToKB(["ingredients", "gruyere cheese", "swiss"])
addToKB(["ingredients", "gouda cheese", "dutch"])
addToKB(["ingredients", "gouda cheese", "dairy"])
addToKB(["ingredients", "gouda cheese", "cheese"])
addToKB(["ingredients", "feta cheese", "greek"])
addToKB(["ingredients", "feta cheese", "dairy"])
addToKB(["ingredients", "feta cheese", "cheese"])
addToKB(["ingredients", "milk", "dairy"])
addToKB(["ingredients", "milk", "liquid"])
addToKB(["ingredients", "brie cheese", "cheese"])
addToKB(["ingredients", "brie cheese", "french"])
addToKB(["ingredients", "brie cheese", "dairy"])
addToKB(["ingredients", "cream cheese", "dairy"])
addToKB(["ingredients", "cream cheese", "cheese"])
addToKB(["ingredients", "cream cheese", "cream"])
addToKB(["ingredients", "ricotta cheese", "italian"])
addToKB(["ingredients", "ricotta cheese", "cheese"])
addToKB(["ingredients", "ricotta cheese", "dairy"])
addToKB(["ingredients", "parmesan cheese", "italian"])
addToKB(["ingredients", "parmesan cheese", "cheese"])
addToKB(["ingredients", "parmesan cheese", "dairy"])
addToKB(["ingredients", "blue cheese", "dairy"])
addToKB(["ingredients", "blue cheese", "cheese"])
addToKB(["ingredients", "blue cheese", "molded"])
addToKB(["ingredients", "cheddar cheese", "hard"])
addToKB(["ingredients", "cheddar cheese", "dairy"])
addToKB(["ingredients", "cheddar cheese", "cheese"])
addToKB(["ingredients", "cheddar cheese", "english"])
addToKB(["ingredients", "mascarpone cheese", "cream"])
addToKB(["ingredients", "mascarpone cheese", "cheese"])
addToKB(["ingredients", "mascarpone cheese", "italian"])
addToKB(["ingredients", "mascarpone cheese", "dairy"])
addToKB(["ingredients", "cream", "cream"])
addToKB(["ingredients", "provolone cheese", "italian"])
addToKB(["ingredients", "provolone cheese", "dairy"])
addToKB(["ingredients", "provolone cheese", "cheese"])
addToKB(["ingredients", "mozzarella cheese", "italian"])
addToKB(["ingredients", "mozzarella cheese", "dairy"])
addToKB(["ingredients", "mozzarella cheese", "cheese"])
addToKB(["ingredients", "khoya", "indian"])
addToKB(["ingredients", "khoya", "dairy"])
addToKB(["ingredients", "khoya", "cheese"])
addToKB(["ingredients", "hung curd", "dairy"])
addToKB(["ingredients", "hung curd", "yogurt"])
addToKB(["ingredients", "yogurt", "yogurt"])
addToKB(["ingredients", "yogurt", "dairy"])
addToKB(["ingredients", "cottage cheese", "curded"])
addToKB(["ingredients", "cottage cheese", "dairy"])
addToKB(["ingredients", "condensed milk", "dairy"])
addToKB(["ingredients", "clarified butter", "fat"])
addToKB(["ingredients", "clarified butter", "dairy"])
addToKB(["ingredients", "buttermilk", "fat"])
addToKB(["ingredients", "buttermilk", "dairy"])
addToKB(["ingredients", "butter", "dairy"])
addToKB(["ingredients", "butter", "fat"])

addToKB(["ingredients", "gold leaf", "garnish"])
addToKB(["ingredients", "gold leaf", "fancy"])
addToKB(["ingredients", "gold leaf", "expensive"])
addToKB(["ingredients", "gold leaf", "thin"])
addToKB(["ingredients", "glycerine", "condiment"])
addToKB(["ingredients", "glycerine", "sweetner"])
addToKB(["ingredients", "glycerine", "syrup"])
addToKB(["ingredients", "glycerine", "colorless"])
addToKB(["ingredients", "glycerine", "perservative"])
addToKB(["ingredients", "gelatin", "jello"])
addToKB(["ingredients", "gelatin", "translucent"])
addToKB(["ingredients", "gelatin", "collagen"])
addToKB(["ingredients", "gelatin", "flavorless"])
addToKB(["ingredients", "fish sauce", "condiment"])
addToKB(["ingredients", "fish sauce", "salty"])
addToKB(["ingredients", "fish sauce", "fermented"])
addToKB(["ingredients", "fish sauce", "sauce"])
addToKB(["ingredients", "fish sauce", "seasoning"])
addToKB(["ingredients", "fish sauce", "chinese"])
addToKB(["ingredients", "desiccated coconut", "flakes"])
addToKB(["ingredients", "desiccated coconut", "dried"])
addToKB(["ingredients", "desiccated coconut", "garnish"])
addToKB(["ingredients", "cranberry sauce", "sauce"])
addToKB(["ingredients", "cranberry sauce", "relish"])
addToKB(["ingredients", "cranberry sauce", "cranberries"])
addToKB(["ingredients", "cranberry sauce", "sweet"])
addToKB(["ingredients", "cranberry sauce", "fruity"])
addToKB(["ingredients", "cornflour", "flour"])
addToKB(["ingredients", "cornflour", "powdery"])
addToKB(["ingredients", "cornflour", "breading"])
addToKB(["ingredients", "cognac", "brandy"])
addToKB(["ingredients", "cognac", "alcohol"])
addToKB(["ingredients", "cognac", "bitter"])
addToKB(["ingredients", "cognac", "grapes"])
addToKB(["ingredients", "cognac", "liquid"])
addToKB(["ingredients", "coconut water", "sweet"])
addToKB(["ingredients", "coconut water", "liquid"])
addToKB(["ingredients", "coconut water", "nutty"])
addToKB(["ingredients", "coconut milk", "liquid"])
addToKB(["ingredients", "coconut milk", "rich"])
addToKB(["ingredients", "coconut milk", "oily"])
addToKB(["ingredients", "coconut milk", "asia"])
addToKB(["ingredients", "cocoa", "chocolate"])
addToKB(["ingredients", "cocoa", "bitter"])
addToKB(["ingredients", "cocoa", "baking"])
addToKB(["ingredients", "cocoa", "dried"])
addToKB(["ingredients", "cocoa", "see"])
addToKB(["ingredients", "cocoa", "black"])
addToKB(["ingredients", "tea", "aromatic"])
addToKB(["ingredients", "tea", "liquid"])
addToKB(["ingredients", "tea", "beverage"])
addToKB(["ingredients", "tea", "leaves"])
addToKB(["ingredients", "tea", "chinese"])
addToKB(["ingredients", "tea", "drink"])
addToKB(["ingredients", "tea", "asian"])
addToKB(["ingredients", "brown sauce", "condiment"])
addToKB(["ingredients", "brown sauce", "brown"])
addToKB(["ingredients", "brown sauce", "tart"])
addToKB(["ingredients", "brown sauce", "sweet"])
addToKB(["ingredients", "brown sauce", "peppery"])
addToKB(["ingredients", "brown sauce", "steak-sauce"])
addToKB(["ingredients", "baking soda", "baking"])
addToKB(["ingredients", "baking soda", "expansion"])
addToKB(["ingredients", "baking soda", "alkaline"])
addToKB(["ingredients", "baking soda", "chemical"])
addToKB(["ingredients", "tofu", "vegetarian"])
addToKB(["ingredients", "tofu", "soybean"])
addToKB(["ingredients", "tofu", "soy"])
addToKB(["ingredients", "tofu", "asian"])
addToKB(["ingredients", "tofu", "savory"])
addToKB(["ingredients", "tofu", "meat-replacement"])
addToKB(["ingredients", "tofu", "curd"])
addToKB(["ingredients", "tofu", "bean"])
addToKB(["ingredients", "tofu", "soft"])
addToKB(["ingredients", "tofu", "white"])
addToKB(["ingredients", "tofu", "bland"])
addToKB(["ingredients", "tofu", "beany"])
addToKB(["ingredients", "baking powder", "yeast"])
addToKB(["ingredients", "baking powder", "baking"])
addToKB(["ingredients", "baking powder", "expansion"])
addToKB(["ingredients", "baking powder", "chemical"])
addToKB(["ingredients", "arrowroot", "indian"])
addToKB(["ingredients", "arrowroot", "plant"])
addToKB(["ingredients", "arrowroot", "starch"])
addToKB(["ingredients", "egg", "oval"])
addToKB(["ingredients", "egg", "embryo"])
addToKB(["ingredients", "egg", "baking"])
addToKB(["ingredients", "egg", "perishable"])
addToKB(["ingredients", "egg", "yolk"])
addToKB(["ingredients", "egg", "protein"])
addToKB(["ingredients", "egg", "bland"])
addToKB(["ingredients", "alum", "condiment"])
addToKB(["ingredients", "alum", "white"])
addToKB(["ingredients", "alum", "preservative"])
addToKB(["ingredients", "marzipan", "confection"])
addToKB(["ingredients", "marzipan", "sugar"])
addToKB(["ingredients", "marzipan", "sweet"])
addToKB(["ingredients", "marzipan", "honey"])
addToKB(["ingredients", "marzipan", "almond"])
addToKB(["ingredients", "marzipan", "asian"])
addToKB(["ingredients", "ajinomoto", "condiment"])
addToKB(["ingredients", "ajinomoto", "seasoning"])
addToKB(["ingredients", "ajinomoto", "japanese"])
addToKB(["ingredients", "ajinomoto", "msg"])
addToKB(["ingredients", "ajinomoto", "chemical"])
addToKB(["ingredients", "ajinomoto", "additive"])
addToKB(["ingredients", "agar", "jelly-like"])
addToKB(["ingredients", "agar", "jelly"])
addToKB(["ingredients", "agar", "algae"])
addToKB(["ingredients", "agar", "vegetarian"])
addToKB(["ingredients", "agar", "odorless"])
addToKB(["ingredients", "agar", "colorless"])
addToKB(["ingredients", "agar", "tasteless"])

addToKB(["ingredients", "olive oil", "oil"])
addToKB(["ingredients", "olive oil", "italian"])
addToKB(["ingredients", "peanut oil", "chinese"])
addToKB(["ingredients", "peanut oil", "oil"])
addToKB(["ingredients", "spaghetti", "italian"])
addToKB(["ingredients", "spaghetti", "pasta"])
addToKB(["ingredients", "lo mein", "chinese"])
addToKB(["ingredients", "lo mein", "pasta"])
addToKB(["ingredients", "parmigiano-reggiano", "dairy"])
addToKB(["ingredients", "parmigiano-reggiano", "cheese"])
addToKB(["ingredients", "parmigiano-reggiano", "italian"])
addToKB(["ingredients", "cilantro", "herb"])
addToKB(["ingredients", "cilantro", "spice"])
addToKB(["ingredients", "cilantro", "chinese"])
addToKB(["ingredients", "pepper flakes", "pepper"])
addToKB(["ingredients", "pepper flakes", "dried"])
addToKB(["ingredients", "pepper flakes", "flakes"])
addToKB(["ingredients", "dried chili pepper", "chinese"])
addToKB(["ingredients", "dried chili pepper", "dried"])
addToKB(["ingredients", "dried chili pepper", "pepper"])
addToKB(["ingredients", "white vinegar", "american"])
addToKB(["ingredients", "white vinegar", "vinegar"])
addToKB(["ingredients", "apple cider vinegar", "american"])
addToKB(["ingredients", "apple cider vinegar", "vinegar"])
addToKB(["ingredients", "wine vinegar", "european"])
addToKB(["ingredients", "wine vinegar", "vinegar"])
addToKB(["ingredients", "balsamic vinegar", "italian"])
addToKB(["ingredients", "balsamic vinegar", "vinegar"])
addToKB(["ingredients", "rice vinegar", "japanese"])
addToKB(["ingredients", "rice vinegar", "vinegar"])
addToKB(["ingredients", "black vinegar", "chinese"])
addToKB(["ingredients", "black vinegar", "vinegar"])
addToKB(["ingredients", "malt vinegar", "british"])
addToKB(["ingredients", "malt vinegar", "vinegar"])
addToKB(["ingredients", "penne", "italian"])
addToKB(["ingredients", "penne", "pasta"])
addToKB(["ingredients", "cornstarch", "grain"])
addToKB(["ingredients", "cornstarch", "corn"])
addToKB(["ingredients", "cornstarch", "additive"])
addToKB(["ingredients", "cornstarch", "powder"])
addToKB(["ingredients", "cornstarch", "starch"])

addToKB(["ingredients", "filet mignon", "meat"])
addToKB(["ingredients", "filet mignon", "beef"])
addToKB(["ingredients", "filet mignon", "tenderloin"])
addToKB(["ingredients", "filet mignon", "protein"])
addToKB(["ingredients", "pork sausage", "meat"])
addToKB(["ingredients", "pork sausage", "pork"])
addToKB(["ingredients", "pork sausage", "chinese"])
addToKB(["ingredients", "beef sausage", "meat"])
addToKB(["ingredients", "beef sausage", "chinese"])
addToKB(["ingredients", "sausage", "meat"])
addToKB(["ingredients", "sausage", "chinese"])
addToKB(["ingredients", "rib-eye", "meat"])
addToKB(["ingredients", "ribs", "meat"])
addToKB(["ingredients", "ribs", "chinese"])
addToKB(["ingredients", "steak", "meat"])
addToKB(["ingredients", "steak", "chinese"])
addToKB(["ingredients", "pepperoni", "meat"])
addToKB(["ingredients", "pepperoni", "italian"])
addToKB(["ingredients", "salami", "meat"])
addToKB(["ingredients", "salami", "italian"])
addToKB(["ingredients", "pastrami", "meat"])
addToKB(["ingredients", "pastrami", "italian"])
addToKB(["ingredients", "meatball", "meat"])
addToKB(["ingredients", "meatball", "italian"])

"""

## Not Tagged

addToKB(["ingredients", "cheese", "category", "dairy products"]) #this is too generic but better than nothing

addToKB(["ingredients", "cranberry", "category", "fruits"])
addToKB(["ingredients", "kiwi", "category", "fruits"])
addToKB(["ingredients", "blueberries", "category", "fruits"])
addToKB(["ingredients", "mango", "category", "fruits"])
addToKB(["ingredients", "watermelon", "category", "fruits"])
addToKB(["ingredients", "tomato", "category", "fruits"])
addToKB(["ingredients", "strawberry", "category", "fruits"])
addToKB(["ingredients", "water chestnut", "category", "fruits"])
addToKB(["ingredients", "papaya", "category", "fruits"])
addToKB(["ingredients", "orange rind", "category", "fruits"])
addToKB(["ingredients", "orange", "category", "fruits"])
addToKB(["ingredients", "olive", "category", "fruits"])
addToKB(["ingredients", "pear", "category", "fruits"])
addToKB(["ingredients", "sultana", "category", "fruits"])
addToKB(["ingredients", "mulberry", "category", "fruits"])
addToKB(["ingredients", "lychee", "category", "fruits"])
addToKB(["ingredients", "lemon juice", "category", "fruits"])
addToKB(["ingredients", "lemon rind", "category", "fruits"])
addToKB(["ingredients", "fruit", "category", "fruits"])
addToKB(["ingredients", "lemon", "category", "fruits"])
addToKB(["ingredients", "raisins", "category", "fruits"])
addToKB(["ingredients", "jamun", "category", "fruits"])
addToKB(["ingredients", "tamarind", "category", "fruits"])
addToKB(["ingredients", "grapefruit", "category", "fruits"])
addToKB(["ingredients", "indian gooseberry", "category", "fruits"])
addToKB(["ingredients", "dried fruit", "category", "fruits"])
addToKB(["ingredients", "dates", "category", "fruits"])
addToKB(["ingredients", "custard apple", "category", "fruits"])
addToKB(["ingredients", "currant", "category", "fruits"])
addToKB(["ingredients", "cooking apples", "category", "fruits"])
addToKB(["ingredients", "coconut", "category", "fruits"])
addToKB(["ingredients", "cherry", "category", "fruits"])
addToKB(["ingredients", "cape gooseberry", "category", "fruits"])
addToKB(["ingredients", "banana", "category", "fruits"])
addToKB(["ingredients", "peach", "category", "fruits"])
addToKB(["ingredients", "apricots", "category", "fruits"])
addToKB(["ingredients", "apples", "category", "fruits"])
addToKB(["ingredients", "figs", "category", "fruits"])
addToKB(["ingredients", "grapes", "category", "fruits"])
addToKB(["ingredients", "pomegranate", "category", "fruits"])
addToKB(["ingredients", "pineapple", "category", "fruits"])
addToKB(["ingredients", "guava", "category", "fruits"])
addToKB(["ingredients", "plum", "category", "fruits"])
addToKB(["ingredients", "berries", "category", "fruits"])
addToKB(["ingredients", "lime", "category", "fruits"])
addToKB(["ingredients", "honeydew", "category", "fruits"])

addToKB(["ingredients", "shrimp", "category", "seafood"])
addToKB(["ingredients", "tuna", "category", "seafood"])
addToKB(["ingredients", "tilapia", "category", "seafood"])
addToKB(["ingredients", "shellfish", "category", "seafood"])
addToKB(["ingredients", "shark", "category", "seafood"])
addToKB(["ingredients", "hilsa", "category", "seafood"])
addToKB(["ingredients", "sardine", "category", "seafood"])
addToKB(["ingredients", "salmon", "category", "seafood"])
addToKB(["ingredients", "prawn", "category", "seafood"])
addToKB(["ingredients", "pomfret", "category", "seafood"])
addToKB(["ingredients", "perch", "category", "seafood"])
addToKB(["ingredients", "pearl spot", "category", "seafood"])
addToKB(["ingredients", "mussel", "category", "seafood"])
addToKB(["ingredients", "mullet", "category", "seafood"])
addToKB(["ingredients", "squid", "category", "seafood"])
addToKB(["ingredients", "haddock", "category", "seafood"])
addToKB(["ingredients", "flounder", "category", "seafood"])
addToKB(["ingredients", "fish stock", "category", "seafood"])
addToKB(["ingredients", "fish", "category", "seafood"])
addToKB(["ingredients", "fish fillet", "category", "seafood"])
addToKB(["ingredients", "cuttle fish", "category", "seafood"])
addToKB(["ingredients", "cod", "category", "seafood"])
addToKB(["ingredients", "clam", "category", "seafood"])
addToKB(["ingredients", "cat fish", "category", "seafood"])
addToKB(["ingredients", "mackerel", "category", "seafood"])
addToKB(["ingredients", "anchovie", "category", "seafood"])
addToKB(["ingredients", "anchovy", "category", "seafood"])
addToKB(["ingredients", "halibut", "category", "seafood"])
addToKB(["ingredients", "oyster", "category", "seafood"])
addToKB(["ingredients", "lobster", "category", "seafood"])
addToKB(["ingredients", "calamari", "category", "seafood"])
addToKB(["ingredients", "scallop", "category", "seafood"])
addToKB(["ingredients", "seaweed", "category", "seafood"])

addToKB(["ingredients", "brown sugar", "category", "sugar and sugar products"])
addToKB(["ingredients", "sugar candy", "category", "sugar and sugar products"])
addToKB(["ingredients", "icing sugar", "category", "sugar and sugar products"])
addToKB(["ingredients", "honey", "category", "sugar and sugar products"])
addToKB(["ingredients", "jaggery", "category", "sugar and sugar products"])
addToKB(["ingredients", "golden syrup", "category", "sugar and sugar products"])
addToKB(["ingredients", "sugar", "category", "sugar and sugar products"])
addToKB(["ingredients", "castor sugar", "category", "sugar and sugar products"])
addToKB(["ingredients", "caramel", "category", "sugar and sugar products"])
addToKB(["ingredients", "cane sugar", "category", "sugar and sugar products"])

addToKB(["ingredients", "canola oil", "category", "nuts and oilseeds"])
addToKB(["ingredients", "chia seeds", "category", "nuts and oilseeds"])
addToKB(["ingredients", "hazelnut", "category", "nuts and oilseeds"])
addToKB(["ingredients", "pine nuts", "category", "nuts and oilseeds"])
addToKB(["ingredients", "mustard oil", "category", "nuts and oilseeds"])
addToKB(["ingredients", "sunflower seed", "category", "nuts and oilseeds"])
addToKB(["ingredients", "sesame oil", "category", "nuts and oilseeds"])
addToKB(["ingredients", "pistachio", "category", "nuts and oilseeds"])
addToKB(["ingredients", "olive oil", "category", "nuts and oilseeds"])
addToKB(["ingredients", "mustard seeds", "category", "nuts and oilseeds"])
addToKB(["ingredients", "poppy seeds", "category", "nuts and oilseeds"])
addToKB(["ingredients", "sesame seeds", "category", "nuts and oilseeds"])
addToKB(["ingredients", "peanuts", "category", "nuts and oilseeds"])
addToKB(["ingredients", "chironji", "category", "nuts and oilseeds"])
addToKB(["ingredients", "cashew", "category", "nuts and oilseeds"])
addToKB(["ingredients", "blanched almonds", "category", "nuts and oilseeds"])
addToKB(["ingredients", "almonds", "category", "nuts and oilseeds"])
addToKB(["ingredients", "walnuts", "category", "nuts and oilseeds"])
addToKB(["ingredients", "cooking spray", "category", "nuts and oilseeds"])
addToKB(["ingredients", "truffle oil", "category", "nuts and oilseeds"])
addToKB(["ingredients", "flax seed", "category", "nuts and oilseeds"])
addToKB(["ingredients", "macadamia nut", "category", "nuts and oilseeds"])

addToKB(["ingredients", "almond milk", "category", "other ingredients"])
addToKB(["ingredients", "red wine vinegar", "category", "other ingredients"])
addToKB(["ingredients", "red wine", "category", "other ingredients"])
addToKB(["ingredients", "margarine", "category", "other ingredients"])
addToKB(["ingredients", "soy milk", "category", "other ingredients"])
addToKB(["ingredients", "white wine", "category", "other ingredients"])
addToKB(["ingredients", "yeast", "category", "other ingredients"])
addToKB(["ingredients", "white pepper", "category", "other ingredients"])
addToKB(["ingredients", "rice vinegar", "category", "other ingredients"])
addToKB(["ingredients", "sea salt", "category", "other ingredients"])
addToKB(["ingredients", "hoisin sauce", "category", "other ingredients"])
addToKB(["ingredients", "malt vinegar", "category", "other ingredients"])
addToKB(["ingredients", "chocolate chips", "category", "other ingredients"])
addToKB(["ingredients", "quinoa", "category", "other ingredients"])
addToKB(["ingredients", "rice flour", "category", "other ingredients"])
addToKB(["ingredients", "polenta", "category", "other ingredients"])
addToKB(["ingredients", "oyster sauce", "category", "other ingredients"])
addToKB(["ingredients", "guchchi", "category", "other ingredients"])
addToKB(["ingredients", "flat noodles", "category", "other ingredients"])
addToKB(["ingredients", "balsamic vinegar", "category", "other ingredients"])
addToKB(["ingredients", "coconut oil", "category", "other ingredients"])
addToKB(["ingredients", "barfi", "category", "other ingredients"])
addToKB(["ingredients", "rice noodles", "category", "other ingredients"])
addToKB(["ingredients", "coffee", "category", "other ingredients"])
addToKB(["ingredients", "beer", "category", "other ingredients"])
addToKB(["ingredients", "chocolate", "category", "other ingredients"])
addToKB(["ingredients", "sake", "category", "other ingredients"])
addToKB(["ingredients", "vinaigrette", "category", "other ingredients"])
addToKB(["ingredients", "vanilla", "category", "other ingredients"])
addToKB(["ingredients", "tortilla", "category", "other ingredients"])
addToKB(["ingredients", "tomato puree", "category", "other ingredients"])
addToKB(["ingredients", "vegetable oil", "category", "other ingredients"])
addToKB(["ingredients", "tartaric acid", "category", "other ingredients"])
addToKB(["ingredients", "soya sauce", "category", "other ingredients"])
addToKB(["ingredients", "vinegar", "category", "other ingredients"])
addToKB(["ingredients", "sharbat", "category", "other ingredients"])
addToKB(["ingredients", "vermicelli", "category", "other ingredients"])
addToKB(["ingredients", "sev", "category", "other ingredients"])
addToKB(["ingredients", "rum", "category", "other ingredients"])
addToKB(["ingredients", "roux", "category", "other ingredients"])
addToKB(["ingredients", "petha", "category", "other ingredients"])
addToKB(["ingredients", "pasta", "category", "other ingredients"])
addToKB(["ingredients", "papad", "category", "other ingredients"])
addToKB(["ingredients", "paan", "category", "other ingredients"])
addToKB(["ingredients", "meringue", "category", "other ingredients"])
addToKB(["ingredients", "mayonnaise", "category", "other ingredients"])
addToKB(["ingredients", "melon seeds", "category", "other ingredients"])
addToKB(["ingredients", "lotus seeds", "category", "other ingredients"])
addToKB(["ingredients", "vetiver", "category", "other ingredients"])
addToKB(["ingredients", "screw pine", "category", "other ingredients"])
addToKB(["ingredients", "jus", "category", "other ingredients"])
addToKB(["ingredients", "jelly", "category", "other ingredients"])
addToKB(["ingredients", "rose water", "category", "other ingredients"])

addToKB(["ingredients", "chilli sauce", "category", "other ingredients"])
addToKB(["ingredients", "catchup", "category", "other ingredients"])
addToKB(["ingredients", "mustard", "category", "other ingredients"])
addToKB(["ingredients", "water", "category", "other ingredients"])
addToKB(["ingredients", "salad dressing", "category", "other ingredients"])
addToKB(["ingredients", "pepper sauce", "category", "other ingredients"])
addToKB(["ingredients", "spaghetti sauce", "category", "other ingredients"])
addToKB(["ingredients", "spaghetti", "category", "other ingredients"])
addToKB(["ingredients", "alfredo sauce", "category", "other ingredients"])
addToKB(["ingredients", "sweet and sour sauce", "category", "other ingredients"])
addToKB(["ingredients", "marshmallow", "category", "other ingredients"])
addToKB(["ingredients", "sprinkles", "category", "other ingredients"])
addToKB(["ingredients", "soy sauce", "category", "other ingredients"])
addToKB(["ingredients", "hot sauce", "category", "other ingredients"])
addToKB(["ingredients", "vegetable bouillon", "category", "other ingredients"])
addToKB(["ingredients", "pizza crust", "category", "other ingredients"])
addToKB(["ingredients", "ramen", "category", "other ingredients"])
addToKB(["ingredients", "cracker", "category", "other ingredients"])
addToKB(["ingredients", "pie crust", "category", "other ingredients"])
addToKB(["ingredients", "lasagna noodle", "category", "other ingredients"])
addToKB(["ingredients", "bean sauce", "category", "other ingredients"])
addToKB(["ingredients", "lime juice", "category", "other ingredients"])
addToKB(["ingredients", "chili sauce", "category", "other ingredients"])
addToKB(["ingredients", "worcestershire sauce", "category", "other ingredients"])
addToKB(["ingredients", "italian dressing", "category", "other ingredients"])
addToKB(["ingredients", "food coloring", "category", "other ingredients"])
addToKB(["ingredients", "marinara sauce", "category", "other ingredients"])
addToKB(["ingredients", "wine", "category", "other ingredients"])
addToKB(["ingredients", "whiskey", "category", "other ingredients"])
addToKB(["ingredients", "vodka", "category", "other ingredients"])
addToKB(["ingredients", "ranch dressing", "category", "other ingredients"])
addToKB(["ingredients", "maple syrup", "category", "other ingredients"])
addToKB(["ingredients", "protein powder", "category", "other ingredients"])
addToKB(["ingredients", "sweetener", "category", "other ingredients"])
addToKB(["ingredients", "barbeque sauce", "category", "other ingredients"])
addToKB(["ingredients", "barbecue sauce", "category", "other ingredients"])
addToKB(["ingredients", "bbq sauce", "category", "other ingredients"])
addToKB(["ingredients", "sandwich roll", "category", "other ingredients"])
addToKB(["ingredients", "baking mix", "category", "other ingredients"])
addToKB(["ingredients", "pizza dough", "category", "other ingredients"])
addToKB(["ingredients", "juice", "category", "other ingredients"])
addToKB(["ingredients", "soda", "category", "other ingredients"])
addToKB(["ingredients", "noodles", "category", "other ingredients"])
addToKB(["ingredients", "baguette", "category", "other ingredients"])
addToKB(["ingredients", "salsa", "category", "other ingredients"])
addToKB(["ingredients", "hollandaise sauce", "category", "other ingredients"])
addToKB(["ingredients", "macaroni", "category", "other ingredients"])
addToKB(["ingredients", "pickle", "category", "other ingredients"])
addToKB(["ingredients", "teriyaki sauce", "category", "other ingredients"])
addToKB(["ingredients", "cacao", "category", "other ingredients"])
addToKB(["ingredients", "applesauce", "category", "other ingredients"])
addToKB(["ingredients", "chicken bouillon", "category", "other ingredients"])
addToKB(["ingredients", "beef bouillon", "category", "other ingredients"])
addToKB(["ingredients", "pork bouillon", "category", "other ingredients"])
addToKB(["ingredients", "vegetable bouillon", "category", "other ingredients"])

####################################################################
### List of Tools

addToKB(["tools", "pot"])
addToKB(["tools", "apple corer"])
addToKB(["tools", "apple cutter"])
addToKB(["tools", "baster"])
addToKB(["tools", "beanpot"])
addToKB(["tools", "biscuit cutter"])
addToKB(["tools", "biscuit press"])
addToKB(["tools", "blow torch"])
addToKB(["tools", "boil over preventer"])
addToKB(["tools", "bottle opener"])
addToKB(["tools", "bowl"])
addToKB(["tools", "bread knife"])
addToKB(["tools", "browning tray"])
addToKB(["tools", "butter curler"])
addToKB(["tools", "cake and pie server"])
addToKB(["tools", "cheese cutter"])
addToKB(["tools", "cheese knife"])
addToKB(["tools", "cheese slicer"])
addToKB(["tools", "cheesecloth"])
addToKB(["tools", "chef's knife"])
addToKB(["tools", "cherry pitter"])
addToKB(["tools", "chinois"])
addToKB(["tools", "clay pot"])
addToKB(["tools", "cleaver"])
addToKB(["tools", "colander"])
addToKB(["tools", "corkscrew"])
addToKB(["tools", "crab cracker"])
addToKB(["tools", "cutting board"])
addToKB(["tools", "dough scraper"])
addToKB(["tools", "edible tableware"])
addToKB(["tools", "egg piercer"])
addToKB(["tools", "egg poacher"])
addToKB(["tools", "egg separator"])
addToKB(["tools", "egg slicer"])
addToKB(["tools", "egg timer"])
addToKB(["tools", "fillet knife"])
addToKB(["tools", "fish scaler"])
addToKB(["tools", "fish slice"])
addToKB(["tools", "flour sifter"])
addToKB(["tools", "food mill"])
addToKB(["tools", "funnel"])
addToKB(["tools", "garlic press"])
addToKB(["tools", "grapefruit knife"])
addToKB(["tools", "grater"])
addToKB(["tools", "gravy strainer"])
addToKB(["tools", "herb chopper"])
addToKB(["tools", "honey dipper"])
addToKB(["tools", "ladle"])
addToKB(["tools", "lame"])
addToKB(["tools", "lemon reamer"])
addToKB(["tools", "lemon squeezer"])
addToKB(["tools", "lobster pick"])
addToKB(["tools", "mandoline"])
addToKB(["tools", "mated colander pot"])
addToKB(["tools", "measuring cup"])
addToKB(["tools", "measuring spoon"])
addToKB(["tools", "meat grinder"])
addToKB(["tools", "meat tenderiser"])
addToKB(["tools", "meat thermometer"])
addToKB(["tools", "melon baller"])
addToKB(["tools", "mezzaluna"])
addToKB(["tools", "microplane"])
addToKB(["tools", "mortar and pestle"])
addToKB(["tools", "nutcracker"])
addToKB(["tools", "nutmeg grater"])
addToKB(["tools", "oven glove"])
addToKB(["tools", "pastry bag"])
addToKB(["tools", "pastry blender"])
addToKB(["tools", "pastry brush"])
addToKB(["tools", "pastry wheel"])
addToKB(["tools", "peel"])
addToKB(["tools", "peeler"])
addToKB(["tools", "pepper mill"])
addToKB(["tools", "pie bird"])
addToKB(["tools", "pizza cutter"])
addToKB(["tools", "potato masher"])
addToKB(["tools", "potato ricer"])
addToKB(["tools", "pot-holder"])
addToKB(["tools", "poultry shears"])
addToKB(["tools", "roller docker"])
addToKB(["tools", "rolling pin"])
addToKB(["tools", "salt shaker"])
addToKB(["tools", "scales"])
addToKB(["tools", "scissors"])
addToKB(["tools", "scoop"])
addToKB(["tools", "sieve"])
addToKB(["tools", "slotted spoon"])
addToKB(["tools", "spatula"])
addToKB(["tools", "spider"])
addToKB(["tools", "sugar thermometer"])
addToKB(["tools", "tamis"])
addToKB(["tools", "tin opener"])
addToKB(["tools", "tomato knife"])
addToKB(["tools", "tongs"])
addToKB(["tools", "trussing needle"])
addToKB(["tools", "twine"])
addToKB(["tools", "whisk"])
addToKB(["tools", "wooden spoon"])
addToKB(["tools", "zester"])
addToKB(["tools", "skillet"])
addToKB(["tools", "microwave"])
addToKB(["wok", "microwave"])

####################################################################
### List of cooking methods

### Dry methods - don't require much water
addToKB(["cooking-methods", "roast", "dry"])
addToKB(["cooking-methods", "bake", "dry"])
addToKB(["cooking-methods", "shir", "dry"])
addToKB(["cooking-methods", "broil", "dry"])
addToKB(["cooking-methods", "deep fat fry", "dry"])
addToKB(["cooking-methods", "deep fry", "dry"])
addToKB(["cooking-methods", "fry", "dry"])
addToKB(["cooking-methods", "saute", "dry"])
addToKB(["cooking-methods", "stir-fry", "dry"])
addToKB(["cooking-methods", "deglaze", "dry"])
addToKB(["cooking-methods", "grill", "dry"])

### Wet methods - requires water
addToKB(["cooking-methods", "bain-marie", "wet"])
addToKB(["cooking-methods", "baste", "wet"])
addToKB(["cooking-methods", "blanch", "wet"])
addToKB(["cooking-methods", "boil", "wet"])
addToKB(["cooking-methods", "clay pot cook", "wet"])
addToKB(["cooking-methods", "poach", "wet"])
addToKB(["cooking-methods", "pressure cook", "wet"])
addToKB(["cooking-methods", "scald", "wet"])
addToKB(["cooking-methods", "simmer", "wet"])
addToKB(["cooking-methods", "sous-vide", "wet"])
addToKB(["cooking-methods", "steam", "wet"])
addToKB(["cooking-methods", "stew", "wet"])
addToKB(["cooking-methods", "temper", "wet"])
addToKB(["cooking-methods", "thermal cook", "wet"])
addToKB(["cooking-methods", "caramelize", "wet"])

####################################################################

### List of cooking-actions
addToKB(["cooking-actions", "cook"])
addToKB(["cooking-actions", "heat"])
addToKB(["cooking-actions", "dab"])
addToKB(["cooking-actions", "trace"])
addToKB(["cooking-actions", "dump"])
addToKB(["cooking-actions", "dash"])
addToKB(["cooking-actions", "unwrap"])
addToKB(["cooking-actions", "turn"])
addToKB(["cooking-actions", "reduce"])
addToKB(["cooking-actions", "mince"])
addToKB(["cooking-actions", "empty"])
addToKB(["cooking-actions", "chill"])
addToKB(["cooking-actions", "serve"])
addToKB(["cooking-actions", "unmold"])
addToKB(["cooking-actions", "halve"])
addToKB(["cooking-actions", "pound"])
addToKB(["cooking-actions", "smash"])
addToKB(["cooking-actions", "wrap"])
addToKB(["cooking-actions", "blend"])
addToKB(["cooking-actions", "nestle"])
addToKB(["cooking-actions", "unlock"])
addToKB(["cooking-actions", "grate"])
addToKB(["cooking-actions", "increase"])
addToKB(["cooking-actions", "bind"])
addToKB(["cooking-actions", "grind"])
addToKB(["cooking-actions", "break"])
addToKB(["cooking-actions", "flatten"])
addToKB(["cooking-actions", "unseal"])
addToKB(["cooking-actions", "crust"])
addToKB(["cooking-actions", "refrigerate"])
addToKB(["cooking-actions", "overlap"])
addToKB(["cooking-actions", "wiggle"])
addToKB(["cooking-actions", "check"])
addToKB(["cooking-actions", "skim"])
addToKB(["cooking-actions", "whip"])
addToKB(["cooking-actions", "distribute"])
addToKB(["cooking-actions", "criss-cross"])
addToKB(["cooking-actions", "tilt"])
addToKB(["cooking-actions", "spray"])
addToKB(["cooking-actions", "plunge"])
addToKB(["cooking-actions", "tear"])
addToKB(["cooking-actions", "secure"])
addToKB(["cooking-actions", "slit"])
addToKB(["cooking-actions", "sift"])
addToKB(["cooking-actions", "lift"])
addToKB(["cooking-actions", "segment"])
addToKB(["cooking-actions", "punch"])
addToKB(["cooking-actions", "soften"])
addToKB(["cooking-actions", "decrease"])
addToKB(["cooking-actions", "apply"])
addToKB(["cooking-actions", "refill"])
addToKB(["cooking-actions", "tap"])
addToKB(["cooking-actions", "position"])
addToKB(["cooking-actions", "rotate"])
addToKB(["cooking-actions", "center"])
addToKB(["cooking-actions", "temper"])
addToKB(["cooking-actions", "pop"])
addToKB(["cooking-actions", "pulse"])
addToKB(["cooking-actions", "shred"])
addToKB(["cooking-actions", "process"])
addToKB(["cooking-actions", "wash"])
addToKB(["cooking-actions", "melt"])
addToKB(["cooking-actions", "save"])
addToKB(["cooking-actions", "assemble"])
addToKB(["cooking-actions", "flip"])
addToKB(["cooking-actions", "seal"])
addToKB(["cooking-actions", "discard"])
addToKB(["cooking-actions", "swirl"])
addToKB(["cooking-actions", "store"])
addToKB(["cooking-actions", "lubricate"])
addToKB(["cooking-actions", "repeat"])
addToKB(["cooking-actions", "throw"])
addToKB(["cooking-actions", "pin"])
addToKB(["cooking-actions", "strain"])
addToKB(["cooking-actions", "invert"])
addToKB(["cooking-actions", "stream"])
addToKB(["cooking-actions", "mash"])
addToKB(["cooking-actions", "pre-heat"])
addToKB(["cooking-actions", "paint"])
addToKB(["cooking-actions", "rest"])
addToKB(["cooking-actions", "adjust"])
addToKB(["cooking-actions", "extract"])
addToKB(["cooking-actions", "scrub"])
addToKB(["cooking-actions", "clean"])
addToKB(["cooking-actions", "incorporate"])
addToKB(["cooking-actions", "submerge"])
addToKB(["cooking-actions", "crumble"])
addToKB(["cooking-actions", "drain"])
addToKB(["cooking-actions", "thin"])
addToKB(["cooking-actions", "crack"])
addToKB(["cooking-actions", "steep"])
addToKB(["cooking-actions", "dice"])
addToKB(["cooking-actions", "thread"])
addToKB(["cooking-actions", "retain"])
addToKB(["cooking-actions", "pour"])
addToKB(["cooking-actions", "smooth"])
addToKB(["cooking-actions", "garnish"])
addToKB(["cooking-actions", "spoon"])
addToKB(["cooking-actions", "shake"])
addToKB(["cooking-actions", "pat"])
addToKB(["cooking-actions", "rinse"])
addToKB(["cooking-actions", "knead"])
addToKB(["cooking-actions", "flick"])
addToKB(["cooking-actions", "shape"])
addToKB(["cooking-actions", "pass"])
addToKB(["cooking-actions", "light"])
addToKB(["cooking-actions", "zest"])
addToKB(["cooking-actions", "cool"])
addToKB(["cooking-actions", "fan"])
addToKB(["cooking-actions", "scoop"])
addToKB(["cooking-actions", "switch"])
addToKB(["cooking-actions", "splash"])
addToKB(["cooking-actions", "lie"])
addToKB(["cooking-actions", "mop"])
addToKB(["cooking-actions", "close"])
addToKB(["cooking-actions", "peel"])
addToKB(["cooking-actions", "thaw"])
addToKB(["cooking-actions", "add"])
addToKB(["cooking-actions", "without"])
addToKB(["cooking-actions", "even"])
addToKB(["cooking-actions", "alternate"])
addToKB(["cooking-actions", "fermentation"])
addToKB(["cooking-actions", "scatter"])
addToKB(["cooking-actions", "spread"])
addToKB(["cooking-actions", "stuff"])
addToKB(["cooking-actions", "unfold"])
addToKB(["cooking-actions", "fold"])
addToKB(["cooking-actions", "chop"])
addToKB(["cooking-actions", "estimate"])
addToKB(["cooking-actions", "skin"])
addToKB(["cooking-actions", "slide"])
addToKB(["cooking-actions", "uncover"])
addToKB(["cooking-actions", "fluff"])
addToKB(["cooking-actions", "start"])
addToKB(["cooking-actions", "push"])
addToKB(["cooking-actions", "avoid"])
addToKB(["cooking-actions", "ferment"])
addToKB(["cooking-actions", "drop"])
addToKB(["cooking-actions", "remember"])
addToKB(["cooking-actions", "freeze"])
addToKB(["cooking-actions", "coat"])
addToKB(["cooking-actions", "arrange"])
addToKB(["cooking-actions", "dollop"])
addToKB(["cooking-actions", "lay"])
addToKB(["cooking-actions", "finish"])
addToKB(["cooking-actions", "deep"])
addToKB(["cooking-actions", "mist"])
addToKB(["cooking-actions", "trim"])
addToKB(["cooking-actions", "balance"])
addToKB(["cooking-actions", "squeeze"])
addToKB(["cooking-actions", "watch"])
addToKB(["cooking-actions", "puncture"])
addToKB(["cooking-actions", "replace"])
addToKB(["cooking-actions", "split"])
addToKB(["cooking-actions", "portion"])
addToKB(["cooking-actions", "place"])
addToKB(["cooking-actions", "grill"])
addToKB(["cooking-actions", "pierce"])
addToKB(["cooking-actions", "stir"])
addToKB(["cooking-actions", "massage"])
addToKB(["cooking-actions", "taper"])
addToKB(["cooking-actions", "whisk"])
addToKB(["cooking-actions", "separate"])
addToKB(["cooking-actions", "rub"])
addToKB(["cooking-actions", "skewer"])
addToKB(["cooking-actions", "reshape"])
addToKB(["cooking-actions", "double-wrap"])
addToKB(["cooking-actions", "snip"])
addToKB(["cooking-actions", "remove"])
addToKB(["cooking-actions", "slip"])
addToKB(["cooking-actions", "reheat"])
addToKB(["cooking-actions", "brush"])
addToKB(["cooking-actions", "cut"])
addToKB(["cooking-actions", "drape"])
addToKB(["cooking-actions", "release"])
addToKB(["cooking-actions", "debone"])
addToKB(["cooking-actions", "select"])
addToKB(["cooking-actions", "open"])
addToKB(["cooking-actions", "glaze"])
addToKB(["cooking-actions", "oil"])
addToKB(["cooking-actions", "stretch"])
addToKB(["cooking-actions", "scrape"])
addToKB(["cooking-actions", "tamp"])
addToKB(["cooking-actions", "crush"])
addToKB(["cooking-actions", "set"])
addToKB(["cooking-actions", "hollow"])
addToKB(["cooking-actions", "combine"])
addToKB(["cooking-actions", "wait"])
addToKB(["cooking-actions", "pull"])
addToKB(["cooking-actions", "thicken"])
addToKB(["cooking-actions", "reselect"])
addToKB(["cooking-actions", "round"])
addToKB(["cooking-actions", "frost"])
addToKB(["cooking-actions", "dry"])
addToKB(["cooking-actions", "attach"])
addToKB(["cooking-actions", "soak"])
addToKB(["cooking-actions", "pry"])
addToKB(["cooking-actions", "pack"])
addToKB(["cooking-actions", "wad"])
addToKB(["cooking-actions", "lower"])
addToKB(["cooking-actions", "reposition"])
addToKB(["cooking-actions", "slice"])
addToKB(["cooking-actions", "puree"])
addToKB(["cooking-actions", "loosen"])
addToKB(["cooking-actions", "taste"])
addToKB(["cooking-actions", "stack"])
addToKB(["cooking-actions", "sweeten"])
addToKB(["cooking-actions", "truss"])
addToKB(["cooking-actions", "trim"])
addToKB(["cooking-actions", "husk"])
addToKB(["cooking-actions", "roll"])
addToKB(["cooking-actions", "flake"])
addToKB(["cooking-actions", "keep"])
addToKB(["cooking-actions", "prick"])
addToKB(["cooking-actions", "moisten"])
addToKB(["cooking-actions", "unroll"])
addToKB(["cooking-actions", "wet"])
addToKB(["cooking-actions", "tie"])
addToKB(["cooking-actions", "draw"])
addToKB(["cooking-actions", "pick"])
addToKB(["cooking-actions", "deflate"])
addToKB(["cooking-actions", "mix"])
addToKB(["cooking-actions", "wipe"])
addToKB(["cooking-actions", "dissolve"])
addToKB(["cooking-actions", "cube"])
addToKB(["cooking-actions", "fill"])
addToKB(["cooking-actions", "season"])
addToKB(["cooking-actions", "prepare"])
addToKB(["cooking-actions", "hoisin"])
addToKB(["cooking-actions", "immerse"])
addToKB(["cooking-actions", "tighten"])
addToKB(["cooking-actions", "scramble"])
addToKB(["cooking-actions", "ration"])
addToKB(["cooking-actions", "plop"])
addToKB(["cooking-actions", "use"])
addToKB(["cooking-actions", "pinch"])
addToKB(["cooking-actions", "measure"])
addToKB(["cooking-actions", "decorate"])
addToKB(["cooking-actions", "top"])
addToKB(["cooking-actions", "layer"])
addToKB(["cooking-actions", "dip"])
addToKB(["cooking-actions", "poke"])
addToKB(["cooking-actions", "snap"])
addToKB(["cooking-actions", "grab"])
addToKB(["cooking-actions", "transfer"])
addToKB(["cooking-actions", "divide"])
addToKB(["cooking-actions", "drizzle"])
addToKB(["cooking-actions", "warm"])
addToKB(["cooking-actions", "marinate"])
addToKB(["cooking-actions", "force"])
addToKB(["cooking-actions", "insert"])
addToKB(["cooking-actions", "hold"])
addToKB(["cooking-actions", "slather"])
addToKB(["cooking-actions", "pressure"])
addToKB(["cooking-actions", "braid"])
addToKB(["cooking-actions", "crimp"])
addToKB(["cooking-actions", "sprinkle"])
addToKB(["cooking-actions", "press"])
addToKB(["cooking-actions", "untie"])
addToKB(["cooking-actions", "whirl"])
addToKB(["cooking-actions", "dampen"])
addToKB(["cooking-actions", "fry"])
addToKB(["cooking-actions", "toss"])
addToKB(["cooking-actions", "beat"])
addToKB(["cooking-actions", "sterilize"])
addToKB(["cooking-actions", "twist"])
addToKB(["cooking-actions", "trickle"])
addToKB(["cooking-actions", "cover"])
addToKB(["cooking-actions", "rewarm"])
addToKB(["cooking-actions", "carve"])
addToKB(["cooking-actions", "stick"])
addToKB(["cooking-actions", "rinse"])



####################################################################
### List of substitutes

####################################################################
### To Vegan

### Vegan substitutes that should not be changed (could be confused with an igredient that must be changed)

addToKB(["substitutes", "vegetarian", "almond milk", "almond milk"])
addToKB(["substitutes", "vegetarian", "coconut milk", "coconut milk"])
addToKB(["substitutes", "vegetarian", "soy milk", "soy milk"])
addToKB(["substitutes", "vegetarian", "cashew milk", "cashew milk"])
addToKB(["substitutes", "vegetarian", "rice milk", "rice milk"])
addToKB(["substitutes", "vegetarian", "oat milk", "oat milk"])
addToKB(["substitutes", "vegetarian", "peanut butter", "peanut butter"])
addToKB(["substitutes", "vegetarian", "eggplant", "eggplant"])
addToKB(["substitutes", "vegetarian", "bread flour", "bread flour"])

### Vegan substitutes
addToKB(["substitutes", "vegetarian", "chicken bouillon", "vegetable bouillon"])
addToKB(["substitutes", "vegetarian", "beef bouillon", "vegetable bouillon"])
addToKB(["substitutes", "vegetarian", "pork bouillon", "vegetable bouillon"])
addToKB(["substitutes", "vegetarian", "chicken broth", "vegetable broth"])
addToKB(["substitutes", "vegetarian", "chicken stock", "vegetable broth"])
addToKB(["substitutes", "vegetarian", "beef broth", "vegetable broth"])
addToKB(["substitutes", "vegetarian", "beef stock", "vegetable broth"])
addToKB(["substitutes", "vegetarian", "beef broth", "vegetable broth"])
addToKB(["substitutes", "vegetarian", "pork stock", "vegetable broth"])
addToKB(["substitutes", "vegetarian", "clam juice", "vegetable broth"])
addToKB(["substitutes", "vegetarian", "fish juice", "vegetable broth"])
addToKB(["substitutes", "vegetarian", "oyster juice", "vegetable broth"])

addToKB(["substitutes", "vegetarian", "ground meat", "textured soy protein"])
addToKB(["substitutes", "vegetarian", "ground beef", "textured soy protein"])
addToKB(["substitutes", "vegetarian", "ground pork", "textured soy protein"])
addToKB(["substitutes", "vegetarian", "pepperoni", "veggie deli slice"])
addToKB(["substitutes", "vegetarian", "pastrami", "veggie deli slice"])
addToKB(["substitutes", "vegetarian", "salami", "veggie deli slice"])
addToKB(["substitutes", "vegetarian", "steak", "portobello mushroom"])
addToKB(["substitutes", "vegetarian", "filet mignon", "portobello mushroom"])
addToKB(["substitutes", "vegetarian", "rib-eye", "portobello mushroom"])
addToKB(["substitutes", "vegetarian", "ribs", "portobello mushroom"])
addToKB(["substitutes", "vegetarian", "burger", "veggie burger"])
addToKB(["substitutes", "vegetarian", "meatball", "veggie meatball"])
addToKB(["substitutes", "vegetarian", "sausage", "veggie sausage"])
addToKB(["substitutes", "vegetarian", "bacon", "veggie bacon"])
addToKB(["substitutes", "vegetarian", "turkey", "soy turkey patties"])
addToKB(["substitutes", "vegetarian", "chicken breast", "soy chicken patties"])
addToKB(["substitutes", "vegetarian", "chicken leg", "soy chicken patties"])
addToKB(["substitutes", "vegetarian", "chicken thigh", "soy chicken patties"])
addToKB(["substitutes", "vegetarian", "chicken", "soy chicken patties"])
addToKB(["substitutes", "vegetarian", "chicken nuggets", "soy chicken nuggets"])
addToKB(["substitutes", "vegetarian", "jerky", "veggie jerky"])
addToKB(["substitutes", "vegetarian", "pork", "tempeh"])
addToKB(["substitutes", "vegetarian", "meat", "veggie deli slice"])
addToKB(["substitutes", "vegetarian", "beef", "veggie deli slice"])
addToKB(["substitutes", "vegetarian", "veal", "veggie deli slice"])
addToKB(["substitutes", "vegetarian", "lamb", "veggie deli slice"])

# TODO: deal with all kinds of seafood.
addToKB(["substitutes", "vegetarian", "tuna", "tempeh"])
addToKB(["substitutes", "vegetarian", "tilapia", "tempeh"])
addToKB(["substitutes", "vegetarian", "sardine", "tempeh"])
addToKB(["substitutes", "vegetarian", "salmon", "tempeh"])
addToKB(["substitutes", "vegetarian", "squid", "tempeh"])
addToKB(["substitutes", "vegetarian", "cod", "tempeh"])
addToKB(["substitutes", "vegetarian", "clam", "tempeh"])
addToKB(["substitutes", "vegetarian", "halibut", "tempeh"])
addToKB(["substitutes", "vegetarian", "anchovy", "tempeh"])
addToKB(["substitutes", "vegetarian", "anchovie", "tempeh"])
addToKB(["substitutes", "vegetarian", "anchovie", "tempeh"])
addToKB(["substitutes", "vegetarian", "anchovie", "tempeh"])
addToKB(["substitutes", "vegetarian", "mackerel", "tempeh"])
addToKB(["substitutes", "vegetarian", "calamari", "tempeh"])
addToKB(["substitutes", "vegetarian", "shrimp", "tofu"])
addToKB(["substitutes", "vegetarian", "shrimp", "tofu", "preparation_change", ""])
addToKB(["substitutes", "vegetarian", "prawn", "tofu"])
addToKB(["substitutes", "vegetarian", "prawn", "tofu", "preparation_change", ""])
addToKB(["substitutes", "vegetarian", "gelatin", "agar flakes"])


####################################################################
### To Vegan

### Vegan substitutes that should not be changed (could be confused with an igredient that must be changed)

addToKB(["substitutes", "vegan", "almond milk", "almond milk"])
addToKB(["substitutes", "vegan", "coconut milk", "coconut milk"])
addToKB(["substitutes", "vegan", "soy milk", "soy milk"])
addToKB(["substitutes", "vegan", "cashew milk", "cashew milk"])
addToKB(["substitutes", "vegan", "rice milk", "rice milk"])
addToKB(["substitutes", "vegan", "oat milk", "oat milk"])
addToKB(["substitutes", "vegan", "peanut butter", "peanut butter"])
addToKB(["substitutes", "vegan", "eggplant", "eggplant"])
addToKB(["substitutes", "vegan", "bread flour", "bread flour"])

### Vegan substitutes
addToKB(["substitutes", "vegan", "chicken bouillon", "vegetable bouillon"])
addToKB(["substitutes", "vegan", "beef bouillon", "vegetable bouillon"])
addToKB(["substitutes", "vegan", "pork bouillon", "vegetable bouillon"])
addToKB(["substitutes", "vegan", "chicken broth", "vegetable broth"])
addToKB(["substitutes", "vegan", "chicken stock", "vegetable broth"])
addToKB(["substitutes", "vegan", "beef broth", "vegetable broth"])
addToKB(["substitutes", "vegan", "beef stock", "vegetable broth"])
addToKB(["substitutes", "vegan", "beef broth", "vegetable broth"])
addToKB(["substitutes", "vegan", "pork stock", "vegetable broth"])
addToKB(["substitutes", "vegan", "clam juice", "vegetable broth"])
addToKB(["substitutes", "vegan", "fish juice", "vegetable broth"])
addToKB(["substitutes", "vegan", "oyster juice", "vegetable broth"])

addToKB(["substitutes", "vegan", "ground meat", "textured soy protein"])
addToKB(["substitutes", "vegan", "ground beef", "textured soy protein"])
addToKB(["substitutes", "vegan", "ground pork", "textured soy protein"])
addToKB(["substitutes", "vegan", "pepperoni", "veggie deli slice"])
addToKB(["substitutes", "vegan", "pastrami", "veggie deli slice"])
addToKB(["substitutes", "vegan", "salami", "veggie deli slice"])
addToKB(["substitutes", "vegan", "steak", "portobello mushroom"])
addToKB(["substitutes", "vegan", "filet mignon", "portobello mushroom"])
addToKB(["substitutes", "vegan", "rib-eye", "portobello mushroom"])
addToKB(["substitutes", "vegan", "ribs", "portobello mushroom"])
addToKB(["substitutes", "vegan", "burger", "veggie burger"])
addToKB(["substitutes", "vegan", "meatball", "veggie meatball"])
addToKB(["substitutes", "vegan", "sausage", "veggie sausage"])
addToKB(["substitutes", "vegan", "bacon", "veggie bacon"])
addToKB(["substitutes", "vegan", "turkey", "soy turkey patties"])
addToKB(["substitutes", "vegan", "chicken breast", "soy chicken patties"])
addToKB(["substitutes", "vegan", "chicken leg", "soy chicken patties"])
addToKB(["substitutes", "vegan", "chicken thigh", "soy chicken patties"])
addToKB(["substitutes", "vegan", "chicken", "soy chicken patties"])
addToKB(["substitutes", "vegan", "chicken nuggets", "soy chicken nuggets"])
addToKB(["substitutes", "vegan", "jerky", "veggie jerky"])
addToKB(["substitutes", "vegan", "pork", "tempeh"])
addToKB(["substitutes", "vegan", "meat", "veggie deli slice"])
addToKB(["substitutes", "vegan", "beef", "veggie deli slice"])
addToKB(["substitutes", "vegan", "veal", "veggie deli slice"])
addToKB(["substitutes", "vegan", "lamb", "veggie deli slice"])

# TODO: deal with all kinds of seafood.
addToKB(["substitutes", "vegan", "tuna", "tempeh"])
addToKB(["substitutes", "vegan", "tilapia", "tempeh"])
addToKB(["substitutes", "vegan", "sardine", "tempeh"])
addToKB(["substitutes", "vegan", "salmon", "tempeh"])
addToKB(["substitutes", "vegan", "squid", "tempeh"])
addToKB(["substitutes", "vegan", "cod", "tempeh"])
addToKB(["substitutes", "vegan", "clam", "tempeh"])
addToKB(["substitutes", "vegan", "halibut", "tempeh"])
addToKB(["substitutes", "vegan", "anchovy", "tempeh"])
addToKB(["substitutes", "vegan", "anchovie", "tempeh"])
addToKB(["substitutes", "vegan", "anchovie", "tempeh"])
addToKB(["substitutes", "vegan", "anchovie", "tempeh"])
addToKB(["substitutes", "vegan", "mackerel", "tempeh"])
addToKB(["substitutes", "vegan", "calamari", "tempeh"])
addToKB(["substitutes", "vegan", "shrimp", "tofu"])
addToKB(["substitutes", "vegan", "shrimp", "tofu", "preparation_change", ""])
addToKB(["substitutes", "vegan", "prawn", "tofu"])
addToKB(["substitutes", "vegan", "prawn", "tofu", "preparation_change", ""])

# TODO: deal with all kinds of dairy food.
addToKB(["substitutes", "vegan", "milk powder", "almond milk powder"])
addToKB(["substitutes", "vegan", "milk", "soy milk"])
addToKB(["substitutes", "vegan", "milk", "rice milk"])

addToKB(["substitutes", "vegan", "ice cream", "soy ice cream"])
addToKB(["substitutes", "vegan", "ice cream", "rice ice cream"])

# TODO: deal with all kinds of cheese.
addToKB(["substitutes", "vegan", "mozzarella cheese", "tofu"])
addToKB(["substitutes", "vegan", "mozzarella", "tofu"])
addToKB(["substitutes", "vegan", "parmesan cheese", "vegan parmesan cheese"])
addToKB(["substitutes", "vegan", "cheese", "crumbled tofu"])
addToKB(["substitutes", "vegan", "cheese", "soaked raw nuts"])
addToKB(["substitutes", "vegan", "cheese", "tofu"])

addToKB(["substitutes", "vegan", "butter", "vegan margarine"])

addToKB(["substitutes", "vegan", "yogurt", "soy yogurt"])
addToKB(["substitutes", "vegan", "yogurt", "coconut yogurt"])
addToKB(["substitutes", "vegan", "yogurt", "almond yogurt"])

addToKB(["substitutes", "vegan", "scrambled egg", "tofu scramble"])

# eggs are a special case for ingredient mesurement and quantity and preparation.
addToKB(["substitutes", "vegan", "egg", "tofu", "measurement_change", "ounces"])
addToKB(["substitutes", "vegan", "egg", "tofu", "quantity_change", "1.4"])
addToKB(["substitutes", "vegan", "egg", "tofu", "preparation_change", ""])

addToKB(["substitutes", "vegan", "egg", "tofu", "if-main-cooking-method", "bake", "applesauce"])
addToKB(["substitutes", "vegan", "egg", "tofu", "if-main-cooking-method", "bake", "applesauce", "measurement_change", "ounces"])
addToKB(["substitutes", "vegan", "egg", "tofu", "if-main-cooking-method", "bake", "applesauce", "quantity_change", "1.4"])
addToKB(["substitutes", "vegan", "egg", "tofu", "if-main-cooking-method", "bake", "applesauce", "preparation_change", ""])

addToKB(["substitutes", "vegan", "egg", "tofu", "if-main-cooking-method", "simmer", "eggplant"])
addToKB(["substitutes", "vegan", "egg", "tofu", "if-main-cooking-method", "poach", "eggplant"])
addToKB(["substitutes", "vegan", "egg", "tofu", "if-main-cooking-method", "boil", "eggplant"])

addToKB(["substitutes", "vegan", "egg", "tofu", "if-preparation", "beaten", "pureed soft tofu"])
addToKB(["substitutes", "vegan", "egg", "tofu", "if-find-in-sentence", "yolks", "insides"])
addToKB(["substitutes", "vegan", "egg", "tofu", "if-find-in-sentence", "yolk", "inside"])
addToKB(["substitutes", "vegan", "egg", "tofu", "if-find-in-sentence", "whites", "outer part"])

addToKB(["substitutes", "vegan", "egg yolk", "tofu", "if-preparation", "beaten", "pureed soft tofu"])
addToKB(["substitutes", "vegan", "yolk", "tofu", "if-preparation", "beaten", "pureed soft tofu"])

addToKB(["substitutes", "vegan", "instant puddings", "dairy free instant pudding"])
addToKB(["substitutes", "vegan", "pudding", "dairy free pudding"])

addToKB(["substitutes", "vegan", "sour cream", "vegan sour cream"])

addToKB(["substitutes", "vegan", "mayonnaise", "vegan mayonnaise"])
addToKB(["substitutes", "vegan", "ketchup", "vegan ketchup"])

addToKB(["substitutes", "vegan", "gelatin", "agar flakes"])

addToKB(["substitutes", "vegan", "honey", "liquid sweetener"])

addToKB(["substitutes", "vegan", "chocolate", "non-dairy chocolate chips"])
addToKB(["substitutes", "vegan", "chocolate", "non-dairy cocoa powders"])

addToKB(["substitutes", "vegan", "hollandaise sauce", "vegan hollandaise sauce"])
addToKB(["substitutes", "vegan", "oyster sauce", "vegetarian oyster sauce"])
addToKB(["substitutes", "vegan", "worcestershire sauce", "organic worcestershire sauce"])

addToKB(["substitutes", "vegan", "bread", "wheat tortilla"])
addToKB(["substitutes", "vegan", "bread toasts", "wheat tortilla"])
addToKB(["substitutes", "vegan", "english muffins", "wheat tortilla"])
addToKB(["substitutes", "vegan", "muffins", "wheat tortilla"])
addToKB(["substitutes", "vegan", "bagel", "wheat tortilla"])
addToKB(["substitutes", "vegan", "baguette", "wheat tortilla"])
addToKB(["substitutes", "vegan", "biscuit", "wheat tortilla"])
addToKB(["substitutes", "vegan", "brioche bun", "wheat tortilla"])
addToKB(["substitutes", "vegan", "brioche", "wheat tortilla"])
addToKB(["substitutes", "vegan", "ciabatta", "wheat tortilla"])
addToKB(["substitutes", "vegan", "naan", "wheat tortilla"])

addToKB(["substitutes", "vegan", "pancake", "vegan pancake"])
addToKB(["substitutes", "vegan", "cracker", "whole wheat cracker"])

####################################################################
### from Vegan

# those are for the inverse tranformation.
addToKB(["substitutes", "from_vegan", "vegetable broth", "beef broth"])
addToKB(["substitutes", "from_vegan", "textured soy protein", "ground meat"])
addToKB(["substitutes", "from_vegan", "portobello mushroom", "steak"])

addToKB(["substitutes", "from_vegan", "vegetable oil", "butter"])
addToKB(["substitutes", "from_vegan", "canola oil", "butter"])
addToKB(["substitutes", "from_vegan", "olive oil", "butter"])
addToKB(["substitutes", "from_vegan", "peanut oil", "butter"])
addToKB(["substitutes", "from_vegan", "coconut oil", "butter"])
addToKB(["substitutes", "from_vegan", "corn oil", "butter"])
addToKB(["substitutes", "from_vegan", "sunflower oil", "butter"])
addToKB(["substitutes", "from_vegan", "safflower oil", "butter"])
addToKB(["substitutes", "from_vegan", "almond oil,", "butter"])

addToKB(["substitutes", "from_vegan", "almond milk", "milk"])
addToKB(["substitutes", "from_vegan", "coconut milk", "milk"])
addToKB(["substitutes", "from_vegan", "soy milk", "milk"])
addToKB(["substitutes", "from_vegan", "cashew milk", "milk"])
addToKB(["substitutes", "from_vegan", "rice milk", "milk"])
addToKB(["substitutes", "from_vegan", "oat milk", "milk"])

addToKB(["substitutes", "from_vegan", "eggplant", "chicken"])
addToKB(["substitutes", "from_vegan", "soy chicken patties", "chicken"])
addToKB(["substitutes", "from_vegan", "soy chicken nuggets", "chicken nuggets"])
addToKB(["substitutes", "from_vegan", "veggie jerky", "jerky"])

addToKB(["substitutes", "from_vegan", "tempeh", "pork"])

addToKB(["substitutes", "from_vegan", "soy ice cream", "ice cream"])
addToKB(["substitutes", "from_vegan", "rice ice cream", "ice cream"])

addToKB(["substitutes", "from_vegan", "crumbled tofu", "cheese"])
addToKB(["substitutes", "from_vegan", "soaked raw nuts", "cheese"])

addToKB(["substitutes", "from_vegan", "agar flakes", "gelatin"])
addToKB(["substitutes", "from_vegan", "liquid sweetener", "honey"])
addToKB(["substitutes", "from_vegan", "soy yogurt", "yogurt"])
addToKB(["substitutes", "from_vegan", "coconut yogurt", "yogurt"])
addToKB(["substitutes", "from_vegan", "almond yogurt", "yogurt"])

addToKB(["substitutes", "from_vegan", "pureed soft tofu", "beaten egg"])
addToKB(["substitutes", "from_vegan", "mashed bananas", "beaten egg"])

####################################################################
### Chinese Style substitutes

addToKB(["substitutes", "toChinese", "olive oil", "peanut oil"])
addToKB(["substitutes", "toChinese", "spaghetti", "lo mein"])
addToKB(["substitutes", "toChinese", "vinegar", "black vinegar"])
addToKB(["substitutes", "toChinese", "red pepper flakes", "dried chili pepper"])
addToKB(["substitutes", "toChinese", "italian parsley", "cilantro"])
addToKB(["substitutes", "toChinese", "parmigiano-reggiano cheese", "fermented bean curd"])
addToKB(["substitutes", "toChinese", "penne", "lo mein"])
addToKB(["substitutes", "toChinese", "mushrooms", "shiitake mushrooms"])

####################################################################
### Healthy substitutes
addToKB(["substitutes", "healthy", "sugar", "unsweetened applesauce"])
addToKB(["substitutes", "healthy", "white sugar", "unsweetened applesauce"])
addToKB(["substitutes", "healthy", "peanut butter", "natural peanut butter"])
addToKB(["substitutes", "healthy", "butter", "unsweetened butter"])
addToKB(["substitutes", "healthy", "milk", "almond milk"])
addToKB(["substitutes", "healthy", "cream", "coconut milk"])
addToKB(["substitutes", "healthy", "soy sauce", "low-sodium soy sauce"])
addToKB(["substitutes", "healthy", "sour cream", "greek yogurt"])
addToKB(["substitutes", "healthy", "mayonnaise", "greek yogurt"])
addToKB(["substitutes", "healthy", "mayonnaise", "hummus"])
addToKB(["substitutes", "healthy", "syrup", "applesauce"])
addToKB(["substitutes", "healthy", "ketchup", "sun-dried tomato hummus"])


addToKB(["substitutes", "healthy", "rice", "brown rice"])
addToKB(["substitutes", "healthy", "white rice", "brown rice"])
addToKB(["substitutes", "healthy", "bread", "whole-wheat bread"])
addToKB(["substitutes", "healthy", "white bread", "whole-wheat bread"])
addToKB(["substitutes", "healthy", "flour", "gluten-free flour"])
addToKB(["substitutes", "healthy", "couscous", "quinoa"])
addToKB(["substitutes", "healthy", "bread crumb", "ground flaxseed"])
addToKB(["substitutes", "healthy", "tortilla", "corn tortilla"])
addToKB(["substitutes", "healthy", "flour tortilla", "corn tortilla"])
addToKB(["substitutes", "healthy", "pita", "Boiled large collard leaf"])
addToKB(["substitutes", "healthy", "penne pasta", "brown rice pasta"])


addToKB(["substitutes", "healthy", "ground beef", "ground turkey"])
addToKB(["substitutes", "healthy", "ground pork", "ground chicken"])
addToKB(["substitutes", "healthy", "bacon", "lean prosciutto"])
addToKB(["substitutes", "healthy", "canadian-style bacon", "lean prosciutto"])
addToKB(["substitutes", "healthy", "sausage", "turkey sausage"])
addToKB(["substitutes", "healthy", "chorizo sausage", "turkey sausage"])


addToKB(["substitutes", "healthy", "vegetable oil", "coconut oil"])
addToKB(["substitutes", "healthy", "olive oil", "coconut oil"])
addToKB(["substitutes", "healthy", "canola oil", "coconut oil"])
addToKB(["substitutes", "healthy", "croutons", "almonds"])
addToKB(["substitutes", "healthy", "potato chips", "pop corn"])
addToKB(["substitutes", "healthy", "white flour", "coconut flour"])
addToKB(["substitutes", "healthy", "chocolate chips", "cacao nibs"])
addToKB(["substitutes", "healthy", "lettuce", "romaine"])
addToKB(["substitutes", "healthy", "iceberg lettuce", "romaine"])
addToKB(["substitutes", "healthy", "tortilla wraps", "lettuce leaves"])
addToKB(["substitutes", "healthy", "oatmeal", "quinoa"])
addToKB(["substitutes", "healthy", "baking fat", "mashed bananas"])
addToKB(["substitutes", "healthy", "french fries", "sweet potato fries"])
addToKB(["substitutes", "healthy", "mashed potatoes", "cauliflower mash"])
addToKB(["substitutes", "healthy", "canned beans", "dry beans"])
addToKB(["substitutes", "healthy", "granola", "nuts"])
addToKB(["substitutes", "healthy", "creamer", "organic whole milk"])
addToKB(["substitutes", "healthy", "bagel", "english muffin"])
addToKB(["substitutes", "healthy", "bagels", "english muffins"])





addToKB(["substitutes", "healthy", "cream cheese", "fat-free cream cheese"])
addToKB(["substitutes", "healthy", "cheddar cheese", "reduced-calorie cheddar cheese"])
addToKB(["substitutes", "healthy", "swiss cheese", "reduced-calorie swiss cheese"])
addToKB(["substitutes", "healthy", "pepper jack", "reduced-calorie pepper jack cheese"])
addToKB(["substitutes", "healthy", "pepper jack cheese", "reduced-calorie pepper jack cheese"])
addToKB(["substitutes", "healthy", "monterey jack", "reduced-calorie monterey jack"])
addToKB(["substitutes", "healthy", "monterey jack cheese", "reduced-calorie monterey jack cheese"])
addToKB(["substitutes", "healthy", "provolone cheese", "reduced-calorie provolone cheese"])
addToKB(["substitutes", "healthy", "parmesan cheese", "reduced-calorie parmesan cheese"])
addToKB(["substitutes", "healthy", "mozarella", "reduced-calorie mozarella"])
addToKB(["substitutes", "healthy", "shredded mozarella", "reduced-calorie shredded mozarella"])
addToKB(["substitutes", "healthy", "mozarella cheese", "reduced-calorie mozarella cheese"])


addToKB(["substitutes", "healthy", "lettuce", "arugula"])
### End of KB
####################################################################

# Testing
if __name__ == "__main__":
    # print(isInKB(["ingredients", "milk"]))
    # print(isInKB(["ingredients", "xx"]))
    # print(isInKB(["cooking-methods", "baking"]))
    # print(isInKB(["cooking-methods", "baking", "dry"]))
    # print(isInKB(["cooking-methods", "baking", "wet"]))
    # print(isInKB(["cooking-methods", "baking", "wet"]))
    # print(isInKB(["cooking-methods", "baking", "wet"]))
    # print(isInKB(["cooking-methods", "bak.*", "dry"], regex=True))
    # print(isInKB(["cooking-methods", "baking", "d.*"], regex=True))
    # print(isInKB(["cooking-methods", ".*", "wet"], regex=True))
    # print(isInKB([".*"], regex=True))

    # prettyPrintKBsubtree(kb_subtree = getKBSubtree(["cooking-methods"]))

    # print("list of ingredients = ")
    # print(list(getKBSubtree(["ingredients"]).keys()))

    print(getKBPrunedByRegex(["ingredients", ".*", "chinese"]))